version: '3'

services:
  app:
    build: .
    env_file:
      - .env
      - .secrets
    command: bash -c "
      uvicorn the_app.main:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - .:/app
    ports:
      - 8080:8080