insert into shakespeare.character (id, name, abbrev, description, speech_count)
values  ('1apparition-mac', 'First Apparition', 'First Apparition', null, 1),
        ('1citizen', 'First Citizen', 'First Citizen', null, 3),
        ('1conspirator', 'First Conspirator', 'First Conspirator', null, 3),
        ('1gentleman-oth', 'First Gentleman', 'First Gentleman', null, 1),
        ('1goth', 'First Goth', 'First Goth', null, 4),
        ('1murderer', 'First Murderer', 'First Murderer', null, 21),
        ('1musician-oth', 'First Musician', 'First Musician', null, 5),
        ('1musician-rj', 'First Musician', 'First Musician', null, 10),
        ('1officer-oth', 'First Officer', 'First Officer', null, 3),
        ('1player-ham', 'First Player', '1Play', null, 8),
        ('1senator-cor', 'First Senator', 'First Senator', null, 33),
        ('1senator-oth', 'First Senator', 'First Senator', 'A senator of Venice', 8),
        ('1servant-rj', 'First Servant', 'First Servant', null, 4),
        ('1servingman', 'First Serving-Man', 'First Serving-Man', null, 5),
        ('1soldier', 'First Soldier', 'First Soldier', null, 8),
        ('1watchman-ma', 'First Watchman', 'First Watchman', null, 6),
        ('1watchman-rj', 'First Watchman', 'First Watchman', null, 6),
        ('1witch-mac', 'First Witch', 'First Witch', null, 23),
        ('2apparition-mac', 'Second Apparition', 'Second Apparition', null, 2),
        ('2conspirator', 'Second Conspirator', 'Second Conspirator', null, 2),
        ('2gentleman-oth', 'Second Gentleman', 'Second Gentleman', null, 5),
        ('2goth', 'Second Goth', 'Second Goth', null, 1),
        ('2murderer', 'Second Murderer', 'Second Murderer', null, 6),
        ('2musician-rj', 'Second Musician', 'Second Musician', null, 3),
        ('2patrician', 'Second Patrician', 'Second Patrician', null, 1),
        ('2senator-cor', 'Second Senator', 'Second Senator', null, 10),
        ('2senator-oth', 'Second Senator', 'Second Senator', 'A senator of Venice', 1),
        ('2servant-rj', 'Second Servant', 'Second Servant', null, 6),
        ('2servingman', 'Second Serving-Man', 'Second Serving-Man', null, 2),
        ('2soldier', 'Second Soldier', 'Second Soldier', null, 1),
        ('2watchman-ma', 'Second Watchman', 'Second Watchman', null, 5),
        ('2watchman-rj', 'Second Watchman', 'Second Watchman', null, 1),
        ('2witch-mac', 'Second Witch', 'Second Witch', null, 15),
        ('3apparition-mac', 'Third Apparition', 'Third Apparition', null, 1),
        ('3conspirator', 'Third Conspirator', 'Third Conspirator', null, 3),
        ('3gentleman-oth', 'Third Gentleman', 'Third Gentleman', null, 4),
        ('3goth', 'Third Goth', 'Third Goth', null, 1),
        ('3murderer', 'Third Murderer', 'Third Murderer', null, 6),
        ('3musician-rj', 'Third Musician', 'Third Musician', null, 1),
        ('3servingman', 'Third Serving-Man', 'Third Serving-Man', null, 2),
        ('3watchman-rj', 'Third Watchman', 'Third Watchman', null, 1),
        ('3witch-mac', 'Third Witch', 'Third Witch', null, 13),
        ('4gentleman-oth', 'Fourth Gentleman', 'Fourth Gentleman', null, 1),
        ('Aaron', 'Aaron', 'AARON', 'a Moor, beloved by Tamora', 57),
        ('Abbot', 'Abbot', 'Abbot', null, 2),
        ('Abergavenny', 'Lord Abergavenny', 'ABERGAVENNY', null, 5),
        ('Abhorson', 'Abhorson', 'ABHORSON', 'an executioner', 13),
        ('abraham-rj', 'Abraham', 'ABRAHAM', 'Servant to Montague', 5),
        ('Achilles', 'Achilles', 'ACHILLES', 'a Greek prince', 74),
        ('adam-ayli', 'Adam', 'ADAM', 'servant to Oliver', 10),
        ('ADRIANA', 'Adriana', 'ADRIANA', 'wife to Antipholus of Ephesus', 79),
        ('Adrian-tem', 'Adrian', 'ADRIAN', 'a lord', 9),
        ('aedile', 'Aedile', 'Aedile', null, 10),
        ('AEGEON', 'Aegeon', 'AEGEON', 'a merchant of Syracuse', 17),
        ('AEMILIA', 'Aemilia', 'AEMILIA', 'wife to Aegeon, an abbess at Ephesus', 16),
        ('Aemilius', 'Aemilius', 'AEMILIUS', 'a noble Roman', 5),
        ('Aeneas', 'Aeneas', 'AENEAS', 'one of the Trojan commanders', 44),
        ('Agamemnon', 'Agamemnon', 'AGAMEMNON', 'the Greek general', 52),
        ('Agrippa', 'Agrippa', 'AGRIPPA', 'friend to Caesar', 28),
        ('aguecheek', 'Sir Andrew Aguecheek', 'SIR ANDREW', null, 88),
        ('Ajax', 'Ajax', 'AJAX', 'a Greek prince', 55),
        ('Alarbus', 'Alarbus', 'ALARBUS', 'son to Tamora', 0),
        ('Alcibiades', 'Alcibiades', 'ALCIBIADES', 'an Athenian captain', 39),
        ('Alexander', 'Alexander', 'ALEXANDER', 'servant to Cressida', 8),
        ('AlexanderIden', 'Alexander Iden', 'IDEN', 'a Kentish gentleman', 9),
        ('Alexas', 'Alexas', 'ALEXAS', 'attendant on Cleopatra', 15),
        ('Alice', 'Alice', 'ALICE', 'a lady attending on Princess Katherine', 22),
        ('All-ac', 'All', 'All', null, 9),
        ('all-aw', 'All', 'All', null, 2),
        ('allcitizens', 'All Citizens', 'All Citizens', null, 1),
        ('AllConspirators', 'All Conspirators', 'All Conspirators', null, 2),
        ('all-cor', 'All', 'All', null, 16),
        ('All-cym', 'All', 'All', null, 1),
        ('AllGoths', 'All the Goths', 'All the Goths', null, 1),
        ('All-h5', 'All', 'All', null, 2),
        ('All-h61', 'All', 'All', null, 1),
        ('All-h62', 'All', 'All', null, 12),
        ('All-h63', 'All', 'All', null, 1),
        ('All-h8', 'All', 'All', null, 1),
        ('all-ham', 'All', 'All', null, 6),
        ('All-jc', 'All', 'All', null, 9),
        ('all-kr2', 'All', 'All', null, 1),
        ('AllLadies', 'All Ladies', 'All Ladies', null, 1),
        ('AllLords', 'All Lords', 'All Lords', null, 3),
        ('AllLords-tim', 'All Lords', 'All Lords', null, 1),
        ('all-mac', 'All', 'ALL', null, 13),
        ('All-mnd', 'All', 'All', null, 2),
        ('all-mv', 'All', 'All', null, 1),
        ('all-mww', 'All', 'All', null, 1),
        ('all-oth', 'All', 'All', null, 2),
        ('AllPeople', 'All The People', 'All The People', null, 1),
        ('All-per', 'All', 'All', null, 2),
        ('All-r3', 'All', 'All', null, 1),
        ('AllServants-tim', 'All Servants', 'All Servants', null, 7),
        ('All-ta', 'All', 'All', null, 3),
        ('All-tc', 'All', 'All', null, 2),
        ('All-tim', 'All', 'All', null, 1),
        ('all-ts', 'All', 'ALL', null, 1),
        ('Alonso', 'Alonso', 'ALONSO', 'king of Naples', 40),
        ('ambassador', 'Ambassador', 'Ambassador', null, 1),
        ('amiens', 'Amiens', 'AMIENS', 'lord attending on the banished Duke', 10),
        ('Andromache', 'Andromache', 'ANDROMACHE', 'wife to Hector', 6),
        ('ANGELO', 'Angelo', 'ANGELO', 'a goldsmith', 31),
        ('Angelo-m4m', 'Angelo', 'ANGELO', 'deputy', 83),
        ('angus', 'Angus', 'ANGUS', 'Nobleman of Scotland', 4),
        ('AnneBullen', 'Anne Bullen', 'QUEEN ANNE', 'Katharine''s maid of honor, afterwards Queen', 18),
        ('annepage', 'Anne Page', 'ANNE PAGE', 'Mistress Page''s daughter', 19),
        ('Another', 'Another', 'ANOTHER', 'Another', 1),
        ('Antenor', 'Antenor', 'ANTENOR', 'one of the Trojan commanders', 0),
        ('Antigonus', 'Antigonus', 'ANTIGONUS', 'a lord of Sicilia', 19),
        ('Antiochus', 'Antiochus', 'ANTIOCHUS', 'king of Antioch', 12),
        ('AntiochusDaughter', 'Daughter of Antiochus', 'Daughter', null, 1),
        ('ANTIPHOLUSEPHESUS', 'Antipholus of Ephesus', 'ANTIPHOLUS OF EPHESUS', 'twin brother of Antipholus of Syracuse, son to Aegeon and Aemilia', 76),
        ('ANTIPHOLUSSYRACUSE', 'Antipholus of Syracuse', 'ANTIPHOLUS OF SYRACUSE', 'twin brother of Antipholus of Ephesus, son to Aegeon and Aemelia', 103),
        ('antonio', 'Antonio', 'ANTONIO', 'Leonato''s brother', 23),
        ('ANTONIO-12', 'Antonio', 'ANTONIO', 'a sea captain, friend to Sebastain', 26),
        ('Antonio-mv', 'Antonio', 'ANTONIO', 'a merchant of Venice', 47),
        ('Antonio-tem', 'Antonio', 'ANTONIO', 'the King''s brother, the usurping Duke of Milan', 57),
        ('Antonio-tg', 'Antonio', 'ANTONIO', 'father to Proteus', 11),
        ('antony', 'Antony', 'ANTONY', '(Marcus Antonius)', 253),
        ('Apemantus', 'Apemantus', 'APEMANTUS', 'a churlish philosopher', 100),
        ('apothecary', 'Apothecary', 'Apothecary', null, 4),
        ('Archidamus', 'Archidamus', 'ARCHIDAMUS', 'a lord of Bohemia', 7),
        ('Ariel', 'Ariel', 'ARIEL', 'an airy spirit', 45),
        ('Artemidorus', 'Artemidorus', 'ARTEMIDORUS', 'of Cnidos, a teacher of rhetoric.', 4),
        ('Arthur', 'Arthur', 'ARTHUR', 'Duke of Bretagne, nephew to the king', 23),
        ('Arviragus', 'Arviragus', 'ARVIRAGUS', 'son to Cymbeline, disguised under the name of Cadwal, supposed son to Morgan', 46),
        ('Attandants-ac', 'Attendants', 'Attendants', null, 1),
        ('Attendant-ac', 'Attendant', 'Attendant', null, 2),
        ('Attendant-cym', 'Attendant', 'Attendant', null, 1),
        ('attendant-mac', 'Attendant', 'ATTENDANT', null, 1),
        ('audrey', 'Audrey', 'AUDREY', 'a country wench', 12),
        ('Aumerle', 'Duke of Aumerle', 'DUKE OF AUMERLE', 'son of the Duke of York', 38),
        ('Autolycus', 'Autolycus', 'AUTOLYCUS', 'a rogue', 67),
        ('Bagot', 'Bagot', 'BAGOT', 'servant to King Richard II', 6),
        ('balthasar', 'Balthasar', 'BALTHASAR', 'Servant to Romeo', 12),
        ('balthasar-ma', 'Balthasar', 'BALTHASAR', 'Attendant on Don Pedro', 11),
        ('Balthasar-mv', 'Balthasar', 'BALTHASAR', 'servant to Portia', 1),
        ('BALTHAZAR', 'Balthazar', 'BALTHAZAR', 'a merchant', 5),
        ('Banditti', 'Banditti', 'Banditti', null, 4),
        ('banquo', 'Banquo', 'BANQUO', 'General of the King''s army', 33),
        ('baptista', 'Baptista Minola', 'BAPTISTA', 'a gentleman of Padua', 68),
        ('bardolph', 'Lord Bardolph', 'LORD BARDOLPH', null, 35),
        ('bardolphlesser', 'Bardolph', 'BARDOLPH', null, 46),
        ('bardolph-mww', 'Bardolph', 'BARDOLPH', 'sharper attending on Falstaff', 14),
        ('Barnardine', 'Barnardine', 'BARNARDINE', 'a dissolute prisoner', 7),
        ('Bassanio', 'Bassanio', 'BASSANIO', 'Antonio''s friend, suitor likewise to Portia', 73),
        ('Basset', 'Basset', 'BASSET', 'of the Red Rose, or Lancaster, faction', 7),
        ('Bassianus', 'Bassianus', 'BASSIANUS', 'brother to Saturninus; in love with Lavinia', 14),
        ('BastardOrleans', 'Bastard of Orleans', 'BASTARD OF ORLEANS', null, 12),
        ('Bates', 'Bates', 'BATES', 'soldier in King Henry''s army', 7),
        ('Bawd', 'Bawd', 'Bawd', null, 43),
        ('Beadle', 'Beadle', 'Beadle', null, 1),
        ('beadle1', 'First Beadle', 'FIRST BEADLE', null, 4),
        ('beadle2', 'Second Beadle', 'SECOND BEADLE', null, 0),
        ('beatrice', 'Beatrice', 'BEATRICE', 'Niece to Leonato', 106),
        ('bedford', 'Duke of Bedford', 'BEDFORD', 'brother to Henry IV, uncle to Henry V', 24),
        ('Belarius', 'Belarius', 'BELARIUS', 'a banished lord, disguised under the name of Morgan', 58),
        ('belch', 'Sir Toby Belch', 'SIR TOBY BELCH', 'uncle to Olivia', 152),
        ('benedick', 'Benedick', 'BENEDICK', 'A young lord of Padua', 134),
        ('benvolio', 'Benvolio', 'BENVOLIO', 'Nephew to Montague, and friend to Romeo', 64),
        ('Berkeley', 'Berkeley', 'BERKELEY', 'a gentleman attending on Lady Anne', 0),
        ('bernardo', 'Bernardo', 'Ber', 'sentinel', 19),
        ('BERTRAM', 'Bertram', 'BERTRAM', 'Count of Rousillon', 102),
        ('Bevis', 'George Bevis', 'BEVIS', 'a follower of Cade', 9),
        ('bianca', 'Bianca', 'BIANCA', null, 29),
        ('bianca-oth', 'Bianca', 'BIANCA', 'Mistress to Cassio', 15),
        ('Bigot', 'Lord Bigot', 'BIGOT', null, 6),
        ('biondello', 'Biondello', 'BIONDELLO', null, 39),
        ('Biron', 'Biron', 'BIRON', 'lord attending on the king', 159),
        ('BishopCarlisle', 'Bishop of Carlisle', 'BISHOP OF CARLISLE', null, 6),
        ('BishopLincoln', 'Bishop Lincoln', 'LINCOLN', null, 2),
        ('Blanch', 'Blanch', 'BLANCH', 'of Spain, niece to King John', 9),
        ('blunt', 'Blunt', 'BLUNT', null, 11),
        ('Blunt-r3', 'Blunt', 'Blunt', null, 3),
        ('Boatswain', 'Boatswain', 'Boatswain', null, 12),
        ('Bolingbroke-h62', 'Bolingbroke', 'BOLINGBROKE', 'a conjurer', 7),
        ('Bona', 'Bona', 'BONA', 'sister to the French Queen', 4),
        ('borachio', 'Borachio', 'BORACHIO', 'Follower of Don Juan', 38),
        ('both-aw', 'Both', 'Both', null, 2),
        ('bothcitizens', 'Both Citizens', 'Both Citizens', null, 1),
        ('both-cor', 'Both', 'Both', null, 3),
        ('Both-h62', 'Both', 'Both', null, 1),
        ('Both-h8', 'Both', 'Both', null, 1),
        ('Both-per', 'Both', 'Both', null, 1),
        ('Both-r3', 'Both', 'Both', null, 3),
        ('Both-tim', 'Both', 'Both', null, 7),
        ('bothtribunes', 'Both Tribunes', 'Both Tribunes', null, 4),
        ('Bottom', 'Bottom', 'BOTTOM', 'a weaver', 59),
        ('Boult', 'Boult', 'BOULT', 'Pandar''s servant', 38),
        ('Bourbon', 'Duke of Bourbon', 'BOURBON', null, 4),
        ('Boyet', 'Boyet', 'BOYET', 'lord attending on the princess of France', 80),
        ('boy-h5', 'Boy', 'Boy', null, 16),
        ('Boy-h61', 'Boy', 'Boy', 'son of the Master-Gunner', 2),
        ('boy-ma', 'Boy', 'Boy', null, 2),
        ('Boy-r3', 'Boy', 'Boy', 'a young son of Clarence', 7),
        ('Boy-tc', 'Boy', 'Boy', 'servant to Troilus', 3),
        ('brabantio', 'Brabantio', 'BRABANTIO', 'A senator of Venice', 30),
        ('Brandon-h8', 'Brandon', 'BRANDON', null, 6),
        ('brothers-h4p2', 'Brothers', 'BROTHERS', null, 1),
        ('Brutus', 'Brutus', 'BRUTUS', '(Marcus Brutus)', 194),
        ('bullcalf', 'Peter Bullcalf', 'BULLCALF', 'country soldier', 5),
        ('Bushy', 'Bushy', 'BUSHY', 'servant to King Richard II', 13),
        ('caithness', 'Caithness', 'CAITHNESS', 'Nobleman of Scotland', 3),
        ('Caius', 'Caius', 'CAIUS', 'kinsman to Titus', 0),
        ('CaiusLucius', 'Caius Lucius', 'CAIUS LUCIUS', 'general of the Roman forces', 25),
        ('Calchas', 'Calchas', 'CALCHAS', 'a Trojan priest, taking part with the Greeks', 4),
        ('Caliban', 'Caliban', 'CALIBAN', 'a savage and deformed slave', 50),
        ('Calpurnia', 'Calpurnia', 'CALPURNIA', 'wife to Caesar', 6),
        ('cambridge', 'Earl of Cambridge', 'CAMBRIDGE', null, 5),
        ('Camillo', 'Camillo', 'CAMILLO', 'a lord of Sicilia', 72),
        ('Campeius', 'Cardinal Campeius', 'CARDINAL CAMPEIUS', null, 14),
        ('Canidius', 'Canidius', 'CANIDIUS', 'lieutenant-general to Antony', 10),
        ('canterbury', 'Archbishop of Canterbury', 'CANTERBURY', null, 18),
        ('Caphis', 'Caphis', 'CAPHIS', 'servant to Timon''s creditors', 14),
        ('Captain-ac', 'Captain', 'Captain', null, 1),
        ('Captain-h61', 'Captain', 'Captain', null, 5),
        ('Captain-h62', 'Captain', 'Captain', null, 11),
        ('captain-kl', 'Captain', 'Capt', null, 5),
        ('Captain-kr2', 'Captain', 'Captain', null, 2),
        ('captain-ta', 'Captain', 'Captain', null, 1),
        ('Capucius', 'Capucius', 'CAPUCIUS', 'Ambassador from the Emperor Charles V', 5),
        ('capulet', 'Capulet', 'CAPULET', 'Head of the house of Capulet', 51),
        ('capulet2', 'Second Capulet', 'Second Capulet', 'An old man, cousin to Capulet', 2),
        ('CardinalBourchier', 'Cardinal Bourchier', 'CARDINAL', 'archbishop of Canterbury', 2),
        ('CardinalPandulph', 'Cardinal Pandulph', 'CARDINAL PANDULPH', 'the Pope''s legate', 23),
        ('Carrier', 'Carrier', 'Carrier', null, 1),
        ('Casca', 'Casca', 'CASCA', 'a conspirator against Caesar', 39),
        ('Cassandra', 'Cassandra', 'CASSANDRA', 'daughter to Priam, a prophetess', 13),
        ('cassio', 'Cassio', 'CASSIO', 'Othello''s lieutenant', 110),
        ('Cassius', 'Cassius', 'CASSIUS', 'a conspirator against Caesar', 140),
        ('Cato', 'Young Cato', 'CATO', 'friend to Brutus', 3),
        ('celia', 'Celia', 'CELIA', 'daughter to Frederick', 108),
        ('Ceres', 'Ceres', 'CERES', 'presented by spirits', 4),
        ('Cerimon', 'Cerimon', 'CERIMON', 'a lord of Ephesus', 23),
        ('Chamberlain', 'Chamberlain', 'Chamberlain', null, 6),
        ('charles-ayli', 'Charles', 'CHARLES', 'wrestler to Frederick', 8),
        ('Charles-h61', 'Charles, King of France', 'CHARLES', 'king of France', 41),
        ('Charmian', 'Charmian', 'CHARMIAN', 'attendant on Cleopatra', 63),
        ('Chatillon', 'Chatillon', 'CHATILLON', 'ambassador from France to King John', 5),
        ('chiefjustice', 'Lord Chief Justice', 'CHIEF JUSTICE', null, 56),
        ('Children-r3', 'Children', 'Children', null, 3),
        ('Chiron', 'Chiron', 'CHIRON', 'son to Tamora', 30),
        ('Chorus-h5', 'Chorus', 'Chorus', null, 6),
        ('Chorus-h8', 'Chorus', 'Chorus', null, 2),
        ('chorus-rj', 'Chorus', 'Chorus', null, 2),
        ('Chorus-tc', 'Chorus', 'Chorus', null, 1),
        ('ChristopherUrswick', 'Christopher Urswick', 'CHRISTOPHER', 'a priest', 2),
        ('cicero', 'Cicero', 'Ciceronis', 'Senator', 4),
        ('Cinna', 'Cinna', 'CINNA', 'a conspirator against Caesar', 11),
        ('CinnaPoet', 'Cinna the Poet', 'CINNA THE POET', null, 8),
        ('citizen', 'Citizen', 'Citizen', null, 3),
        ('citizens', 'Citizens', 'Citizens', null, 17),
        ('Citizens-jc', 'Citizens', 'Citizens', null, 2),
        ('Citizens-r3', 'Citizens', 'Citizens', null, 0),
        ('claudio', 'Claudio', 'CLAUDIO', 'A young lord of Florence', 125),
        ('Claudio-m4m', 'Claudio', 'CLAUDIO', 'a young gentleman', 35),
        ('claudius', 'Claudius', 'King', 'King of Denmark', 106),
        ('Claudius-jc', 'Claudius', 'CLAUDIUS', 'servant to Brutus', 2),
        ('Cleomenes', 'Cleomenes', 'CLEOMENES', 'a lord of Sicilia', 7),
        ('Cleon', 'Cleon', 'CLEON', 'governor of Tarsus', 19),
        ('Cleopatra', 'Cleopatra', 'CLEOPATRA', 'queen of Egypt', 204),
        ('ClerkChatham', 'Clerk of Chatham', 'Clerk', null, 2),
        ('Clerk-mv', 'Clerk', 'Clerk', null, 1),
        ('Clitus', 'Clitus', 'CLITUS', 'servant to Brutus', 8),
        ('Cloten', 'Cloten', 'CLOTEN', 'son to the Queen by a former husband', 77),
        ('clown1-ham', 'First Clown', 'Clown', null, 34),
        ('clown2-ham', 'Second Clown', 'Other', null, 12),
        ('Clown-ac', 'Clown', 'Clown', null, 8),
        ('Clown-aw', 'Clown', 'Clown', 'servant to the Countess', 58),
        ('clown-oth', 'Clown', 'Clown', 'Servant to Othello', 14),
        ('clown-ta', 'Clown', 'Clown', null, 12),
        ('Clown-wt', 'Clown', 'Clown', 'son of the old Shepherd', 64),
        ('Cobweb', 'Cobweb', 'COBWEB', 'a fairy', 4),
        ('colville', 'Sir John Colville', 'COLVILLE', null, 5),
        ('cominius', 'Cominius', 'COMINIUS', 'general against the Volscians', 67),
        ('Commons', 'Commons', 'Commons', null, 2),
        ('conrade', 'Conrade', 'CONRADE', 'Follower of Don Juan', 23),
        ('Constable', 'Constable of France', 'Constable', null, 40),
        ('Constance', 'Constance', 'CONSTANCE', 'mother to Arthur', 36),
        ('cordelia', 'Cordelia', 'Cor', 'daughter to Lear', 31),
        ('corin', 'Corin', 'CORIN', 'shepherd', 24),
        ('coriolanus', 'Coriolanus', 'CORIOLANUS', 'previously Caius Marcius Coriolanus', 189),
        ('cornelius', 'Cornelius', 'Cor', 'courtier', 1),
        ('Cornelius-cym', 'Cornelius', 'CORNELIUS', 'a physician', 13),
        ('Costard', 'Costard', 'COSTARD', 'a clown', 83),
        ('CountessAuvergne', 'Countess of Auvergne', 'COUNTESS OF AUVERGNE', null, 13),
        ('Countess-aw', 'Countess', 'COUNTESS', 'mother to Bertram', 87),
        ('Court', 'Court', 'COURT', 'soldier in King Henry''s army', 1),
        ('Courtezan', 'Courtezan', 'Courtezan', null, 11),
        ('Cranmer', 'Archbishop Cranmer', 'CRANMER', 'Archbishop of Canterbury', 21),
        ('Cressida', 'Cressida', 'CRESSIDA', 'daughter to Calchas', 152),
        ('Crier-h8', 'Crier', 'Crier', null, 3),
        ('Cromwell', 'Cromwell', 'CROMWELL', 'servant to Wolsey', 21),
        ('Cupid', 'Cupid', 'Cupid', null, 1),
        ('curan', 'Curan', 'Cur', 'a courtier', 4),
        ('CURIO', 'Curio', 'CURIO', 'gentleman attending on the Duke', 4),
        ('curtis', 'Curtis', 'CURTIS', null, 20),
        ('cymbeline', 'Cymbeline', 'CYMBELINE', 'king of Britain', 81),
        ('Dardanius', 'Dardanius', 'DARDANIUS', 'servant to Brutus', 3),
        ('dauphin', 'Lewis the Dauphin', 'DAUPHIN', null, 31),
        ('davy', 'Davy', 'DAVY', 'servant to Shallow', 14),
        ('Decius Brutus', 'Decius Brutus', 'DECIUS BRUTUS', 'a conspirator against Caesar', 12),
        ('Deiphobus', 'Deiphobus', 'DEIPHOBUS', 'son of Priam, king of Troy', 2),
        ('Demetrius', 'Demetrius', 'Demetrius', 'son to Tamora', 39),
        ('Demetrius-ac', 'Demetrius', 'DEMETRIUS', 'friend to Antony', 2),
        ('Demetrius-mnd', 'Demetrius', 'DEMETRIUS', 'in love with Hermia', 48),
        ('dennis', 'Dennis', 'DENNIS', 'shepherd', 2),
        ('Denny', 'Sir Anthony Denny', 'DENNY', null, 3),
        ('Dercetas', 'Dercetas', 'DERCETAS', 'friend to Antony', 5),
        ('desdemona', 'Desdemona', 'DESDEMONA', 'Daughter to Brabantio and wife to Othello', 165),
        ('DIANA', 'Diana', 'DIANA', 'daughter to the Widow', 44),
        ('Diana-per', 'Diana', 'DIANA', null, 1),
        ('DickButcher', 'Dick the Butcher', 'DICK', 'a follower of Cade', 24),
        ('Diomedes', 'Diomedes', 'DIOMEDES', 'attendant on Cleopatra', 7),
        ('Diomedes-tc', 'Diomedes', 'DIOMEDES', 'a Greek prince', 54),
        ('Dion', 'Dion', 'DION', 'a lord of Sicilia', 4),
        ('Dionyza', 'Dionyza', 'DIONYZA', 'wife to Cleon', 19),
        ('DocButts', 'Doctor Butts', 'DOCTOR BUTTS', 'physician to the King', 4),
        ('doctorcaius', 'Doctor Caius', 'DOCTOR CAIUS', 'a French physician', 49),
        ('doctor-kl', 'Doctor', 'Doct', null, 8),
        ('doctor-mac', 'Doctor', 'Doctor', null, 20),
        ('dogberry', 'Dogberry', 'DOGBERRY', 'A constable', 52),
        ('Dolabella', 'Dolabella', 'DOLABELLA', 'friend to Caesar', 23),
        ('DomitiusEnobarus', 'Domitius Enobarus', 'DOMITIUS ENOBARBUS', 'friend to Antony', 113),
        ('DonAdriano', 'Don Adriano de Armado', 'DON ADRIANO DE ARMADO', 'a fantastical Spaniard', 102),
        ('donalbain', 'Donalbain', 'DONALBAIN', 'Son of Duncan', 3),
        ('donjohn', 'Don John', 'DON JOHN', 'The prince''s bastard brother', 40),
        ('donpedro', 'Don Pedro', 'DON PEDRO', 'Prince of Arragon', 135),
        ('Dorcas', 'Dorcas', 'DORCAS', 'a shepherdess', 11),
        ('drawer2', 'Second Drawer', 'SECOND DRAWER', null, 2),
        ('drawer3', 'Third Drawer', 'THIRD DRAWER', null, 2),
        ('DROMIOEPHESUS', 'Dromio of Ephesus', 'DROMIO OF EPHESUS', 'twin brother to Dromio of Syracuse, and attendant on the two Antipholuses', 63),
        ('DROMIOSYRACUSE', 'Dromio of Syracuse', 'DROMIO OF SYRACUSE', 'twin brother to Dromio of Ephesus, and attendant on the two Antipholuses', 99),
        ('DuchessGloucester', 'Duchess of Gloucester', 'DUCHESS', null, 4),
        ('DuchessYork', 'Duchess of York', 'DUCHESS OF YORK', null, 28),
        ('DuchessYork-r3', 'Duchess of York', 'DUCHESS of YORK', 'mother to King Edward IV', 43),
        ('Duke', 'Duke', 'DUKE', 'of Venice', 18),
        ('dukealbany', 'Duke of Albany', 'Alb', null, 58),
        ('DukeAlencon', 'Duke of Alencon', 'ALENCON', null, 18),
        ('duke-ayli', 'Duke', 'DUKE SENIOR', 'living in exile', 32),
        ('DukeBuckingham', 'Duke of Buckingham', 'BUCKINGHAM', null, 26),
        ('DukeBuckingham-h6', 'Duke of Buckingham', 'BUCKINGHAM', null, 115),
        ('dukeburgundy', 'Duke of Burgundy', 'Bur', null, 5),
        ('dukeburgundy-h5', 'Duke of Burgundy', 'BURGUNDY', null, 25),
        ('dukecornwall', 'Duke of Cornwall', 'Corn', null, 53),
        ('dukeflorence', 'Duke of Florence', 'DUKE', null, 6),
        ('dukemilan', 'Duke of Milan', 'DUKE', 'father to Silvia', 48),
        ('DukeNorfolk', 'Duke of Norfolk', 'NORFOLK', null, 48),
        ('DukeNorfolk-h63', 'Duke of Norfolk', 'NORFOLK', null, 11),
        ('DukeSuffolk', 'Duke of Suffolk', 'SUFFOLK', null, 30),
        ('DukeSurrey', 'Duke of Surrey', 'DUKE OF SURREY', null, 3),
        ('dukevenice', 'Duke of Venice', 'DUKE OF VENICE', null, 25),
        ('Dull', 'Dull', 'DULL', 'a constable', 15),
        ('Dumain', 'Dumain', 'DUMAIN', 'lord attending on the king', 54),
        ('duncan', 'Duncan', 'DUNCAN', 'King of Scotland', 18),
        ('EarlDouglas', 'Earl of Douglas', 'Earl of Douglas', null, 19),
        ('earlkent', 'Earl of Kent', 'Kent', null, 127),
        ('earlnorth', 'Earl of Northumberland', 'NORTHUMBERLAND', null, 66),
        ('EarlNorthumberland', 'Earl of Northumberland', 'NORTHUMBERLAND', null, 15),
        ('EarlOxford', 'Earl Oxford', 'OXFORD', null, 14),
        ('EarlRichmond', 'Henry, Earl of Richmond', 'HENRY OF RICHMOND', 'a youth', 0),
        ('EarlSuffolk', 'Earl of Suffolk', 'SUFFOLK', null, 108),
        ('EarlSurrey', 'Earl of Surrey', 'SURREY', null, 24),
        ('EarlSurrey-r3', 'Earl of Surrey', 'SURREY', 'son of the Duke of Norfolk', 1),
        ('EarlWestmoreland-h63', 'Earl of Westmoreland', 'WESTMORELAND', null, 6),
        ('edgar', 'Edgar', 'Edg', 'son of Glouchester', 98),
        ('EdmondRutland', 'Edmond, Earl of Rutland', 'RUTLAND', null, 7),
        ('edmund', 'Edmund', 'Edm', 'bastard son to Glouchester', 79),
        ('EdmundLangley', 'Edmund of Langley', 'DUKE OF YORK', 'duke of York, uncle to the king', 54),
        ('EdmundMortimer', 'Edmund Mortimer', 'MORTIMER', 'Earl of March', 9),
        ('EdwardPlantagenet', 'King Edward IV (Plantagenet)', 'EDWARD', null, 144),
        ('Egeus', 'Egeus', 'EGEUS', 'father to Hermia', 7),
        ('Eglamour', 'Eglamour', 'EGLAMOUR', 'agent for Silvia in her escape', 8),
        ('Egyptian', 'Egyptian', 'Egyptian', null, 2),
        ('Elbow', 'Elbow', 'ELBOW', 'a simple constable', 28),
        ('Eleanor', 'Eleanor', 'DUCHESS', 'duchess of Gloucester', 21),
        ('ely', 'Bishop of Ely', 'ELY', null, 12),
        ('emilia', 'Emilia', 'EMILIA', 'Wife to Iago', 103),
        ('Emilia-wt', 'Emilia', 'EMILIA', 'a lady attending on Hermione', 4),
        ('EnglishHerald', 'English Herald', 'English Herald', null, 1),
        ('Eros', 'Eros', 'EROS', 'friend to Antony', 27),
        ('erpingham', 'Sir Thomas Erpingham', 'ERPINGHAM', null, 5),
        ('escalus', 'Prince Escalus', 'PRINCE', 'Prince of Verona', 16),
        ('Escalus-m4m', 'Escalus', 'ESCALUS', 'Escalus', 78),
        ('Escanes', 'Escanes', 'ESCANES', 'a lord of Tyre', 2),
        ('Essex', 'Essex', 'ESSEX', 'earl of Essex', 1),
        ('Euphronius', 'Euphronius', 'EUPHRONIUS', 'an ambassador from Antony to Caesar', 5),
        ('exeter', 'Duke of Exeter', 'EXETER', 'uncle to Henry IV, great-uncle to Henry V', 46),
        ('Exton', 'Sir Pierce of Exton', 'EXTON', null, 6),
        ('FABIAN-12', 'Fabian', 'FABIAN', 'servant to Olivia', 51),
        ('Fairy', 'Fairy', 'Fairy', null, 4),
        ('falstaff', 'Falstaff', 'FALSTAFF', 'Sir John Falstaff', 471),
        ('fang', 'Fang', 'FANG', 'a Sheriff''s officer', 7),
        ('Father', 'Father', 'Father', 'who has killed his son', 4),
        ('Faulconbridge', 'Faulconbridge', 'ROBERT', 'son of Sir Robert Faulconbridge', 4),
        ('feeble', 'Francis Feeble', 'FEEBLE', 'country soldier', 7),
        ('fenton', 'Fenton', 'FENTON', 'a gentleman', 20),
        ('Ferdinand', 'Ferdinand', 'FERDINAND', 'king of Navarre', 117),
        ('Ferdinand-tem', 'Ferdinand', 'FERDINAND', 'son to the King of Naples', 31),
        ('FESTE', 'Feste', 'Clown', 'a clown, servant to Olivia', 104),
        ('FifthCitizen', 'Fifth Citizen', 'Fifth Citizen', null, 1),
        ('FirstAmbassador-h5', 'First Ambassador', 'First Ambassador', null, 2),
        ('FirstAttendant', 'First Attendant', 'First Attendant', null, 3),
        ('FirstBandit', 'First Bandit', 'First Bandit', null, 5),
        ('FirstBrother', 'First Brother', 'First Brother', 'an apparition', 2),
        ('FirstCaptain-cym', 'First British Captain', 'First Captain', null, 2),
        ('FirstCarrier', 'First Carrier', 'First Carrier', null, 8),
        ('FirstCitizen', 'First Citizen', 'First Citizen', null, 33),
        ('FirstCitizen-h62', 'First Citizen', 'First Citizen', null, 1),
        ('FirstCitizen-jc', 'First Citizen', 'First Citizen', null, 18),
        ('FirstCitizen-kjo', 'First Citizen', 'First Citizen', null, 10),
        ('FirstCitizen-r3', 'First Citizen', 'First Citizen', null, 7),
        ('FirstCommoner', 'First Commoner', 'First Commoner', null, 1),
        ('FirstExecutioner', 'First Executioner', 'First Executioner', null, 2),
        ('FirstFish', 'First Fisherman', 'First Fisherman', null, 15),
        ('FirstGaoler', 'First Gaoler', 'First Gaoler', null, 9),
        ('FirstGaoler-h61', 'First Gaoler', 'First Gaoler', null, 2),
        ('FirstGentleman', 'First Gentleman', 'First Gentleman', null, 12),
        ('FirstGentleman-aw', 'First Gentleman', 'First Gentleman', null, 7),
        ('FirstGentleman-cym', 'First Gentleman', 'First Gentleman', 'a gentleman of Cymbeline''s court', 10),
        ('FirstGentleman-h62', 'First Gentleman', 'First Gentleman', null, 4),
        ('FirstGentleman-h8', 'First Gentleman', 'First Gentleman', null, 34),
        ('FirstGentleman-wt', 'First Gentleman', 'First Gentleman', null, 6),
        ('FirstGent-per', 'First Gentleman', 'First Gentleman', null, 10),
        ('FirstGuard', 'First Guard', 'First Guard', null, 11),
        ('FirstHerald-kr2', 'First Herald', 'First Herald', null, 1),
        ('FirstKeeper', 'First Keeper', 'First Keeper', null, 7),
        ('FirstKnight-per', 'First Knight', 'First Knight', null, 2),
        ('FirstLady', 'First Lady', 'First Lady', null, 1),
        ('FirstLady-cym', 'First Lady', 'First Lady', null, 2),
        ('FirstLady-wt', 'First Lady', 'First Lady', null, 4),
        ('FirstLord', 'First Lord', 'First Lord', null, 4),
        ('FirstLord-aw', 'First Lord', 'First Lord', null, 48),
        ('firstlord-ayli', 'First Lord', 'FIRST LORD', null, 6),
        ('FirstLord-cym', 'First Lord', 'First Lord', 'a lord of Cymbeline''s court', 15),
        ('FirstLord-lll', 'First Lord', 'First Lord', null, 2),
        ('FirstLord-per', 'First Lord', 'First Lord', null, 9),
        ('FirstLord-tim', 'First Lord', 'First Lord', null, 28),
        ('FirstLord-wt', 'First Lord', 'First Lord', null, 14),
        ('FirstMerchant', 'First Merchant', 'First Merchant', 'friend to Antipholus of Syracuse', 3),
        ('FirstMessenger-h63', 'First Messenger', 'First Messenger', null, 1),
        ('FirstMurderer-h62', 'First Murderer', 'First Murderer', null, 4),
        ('FirstMurderer-r3', 'First Murderer', 'First Murderer', null, 33),
        ('FirstNeighbour-h62', 'First Neighbour', 'First Neighbour', null, 1),
        ('FirstOfficer-12', 'First Officer', 'First Officer', null, 5),
        ('FirstOfficer-ac', 'First Officer', 'First Officer', null, 0),
        ('FirstOfficer-cor', 'First Officer', 'First Officer', null, 4),
        ('FirstOutlaw', 'First Outlaw', 'First Outlaw', null, 11),
        ('FirstPetitioner-h62', 'First Petitioner', 'First Petitioner', null, 3),
        ('FirstPirate', 'First Pirate', 'First Pirate', null, 2),
        ('FirstPrentice', 'First ''Prentice', 'First ''Prentice', null, 0),
        ('FirstRoman', 'First Roman', 'First Roman', null, 1),
        ('FirstSailor-per', 'First Sailor', 'First Sailor', null, 4),
        ('FirstSecretary', 'First Secretary', 'First Secretary', 'to Wolsey', 2),
        ('FirstSenator', 'First Senator', 'First Senator', null, 27),
        ('FirstSenator-cym', 'First Senator', 'First Senator', null, 2),
        ('FirstSentinel', 'First Sentinel', 'First Sentinel', null, 1),
        ('FirstServant-ac', 'First Servant', 'First Servant', null, 4),
        ('FirstServant-mww', 'First Servant', 'First Servant', null, 2),
        ('FirstServant-per', 'First Servant', 'First Servant', null, 3),
        ('FirstServant-tim', 'First Servant', 'First Servant', null, 7),
        ('FirstServant-wt', 'First Servant', 'First Servant', null, 2),
        ('FirstServiceman', 'First Serviceman', 'First Serviceman', null, 0),
        ('FirstServingman', 'First Servingman', 'First Servingman', null, 19),
        ('FirstSoldier-ac', 'First Soldier', 'First Soldier', null, 14),
        ('FirstSoldier-aw', 'First Soldier', 'First Soldier', null, 37),
        ('FirstSoldier-h61', 'First Soldier', 'First Soldier', null, 1),
        ('FirstSoldier-jc', 'First Soldier', 'First Soldier', null, 4),
        ('FirstStranger', 'First Stranger', 'First Stranger', null, 4),
        ('FirstTraveller', 'First Traveller', 'First Traveller', null, 1),
        ('FirstTribune', 'First Tribune', 'First Tribune', null, 3),
        ('FirstWarder', 'First Warder', 'First Warder', null, 2),
        ('FirstWatchman-h63', 'First Watchman', 'First Watchman', null, 5),
        ('Flaminius-tim', 'Flaminius', 'Flaminius', null, 10),
        ('Flavius', 'Flavius', 'FLAVIUS', 'steward to Timon', 41),
        ('Flavius-jc', 'Flavius', 'FLAVIUS', 'a tribune', 5),
        ('fleance', 'Fleance', 'FLEANCE', 'Son to Banquo', 2),
        ('Florizel', 'Florizel', 'FLORIZEL', 'prince of Bohemia', 45),
        ('fluellen', 'Fluellen', 'FLUELLEN', null, 68),
        ('Flute', 'Flute', 'FLUTE', 'a bellows-mender', 18),
        ('fool-kl', 'Fool', 'Fool', null, 58),
        ('Fool-tim', 'Fool', 'Fool', null, 9),
        ('ford', 'Ford', 'FORD', 'a gentleman dwelling at Windsor', 99),
        ('Forester', 'Forester', 'Forester', null, 4),
        ('fortinbras', 'Fortinbras', 'Fort', 'Prince of Norway', 6),
        ('FourthCitizen', 'Fourth Citizen', 'Fourth Citizen', null, 3),
        ('FourthCitizen-jc', 'Fourth Citizen', 'Fourth Citizen', null, 16),
        ('FourthLord', 'Fourth Lord', 'Fourth Lord', null, 3),
        ('FourthLord-aw', 'Fourth Lord', 'Fourth Lord', null, 1),
        ('FourthMessenger', 'Fourth Messenger', 'Fourth Messenger', null, 1),
        ('FourthSoldier-ac', 'Fourth Soldier', 'Fourth Soldier', null, 3),
        ('Francisca', 'Francisca', 'FRANCISCA', 'a nun', 2),
        ('francisco', 'Francisco', 'Fran', 'a soldier', 8),
        ('Francisco-tem', 'Francisco', 'FRANCISCO', 'a lord', 2),
        ('francis-h4p2', 'Francis', 'FRANCIS', 'a drawer', 18),
        ('frederick', 'Frederick', 'FREDERICK', 'the Duke''s brother, and usurper of his dominions', 20),
        ('FrenchHerald', 'French Herald', 'French Herald', null, 1),
        ('frenchking', 'King of France', 'FRENCH KING', 'Charles VI', 19),
        ('Frenchman', 'Frenchman', 'Frenchman', 'friend to Philario', 7),
        ('FrenchSoldier', 'French Soldier', 'French Soldier', null, 10),
        ('friarfrancis', 'Friar Francis', 'FRIAR FRANCIS', null, 16),
        ('friarjohn', 'Friar John', 'FRIAR JOHN', 'Franciscan friar', 4),
        ('friarlaurence', 'Friar Laurence', 'FRIAR LAURENCE', 'Franciscan friar', 55),
        ('FriarPeter', 'Friar Peter', 'FRIAR PETER', null, 7),
        ('FriarThomas', 'Friar Thomas', 'FRIAR THOMAS', null, 3),
        ('Froth', 'Froth', 'FROTH', 'a foolish gentleman', 8),
        ('gadshill', 'Gadshill', 'Gadshill', null, 17),
        ('Gallus', 'Gallus', 'GALLUS', 'friend to Caesar', 1),
        ('Gaoler', 'Gaoler', 'Gaoler', null, 1),
        ('Gaoler-wt', 'Gaoler', 'Gaoler', null, 6),
        ('Gardener', 'Gardener', 'Gardener', null, 6),
        ('Gardiner', 'Gardiner', 'GARDINER', 'bishop of Winchester', 22),
        ('Garter', 'Garter', 'Garter', 'King-at-Arms', 1),
        ('garterhost', 'Host', 'Host', 'host of the Garter Inn', 46),
        ('General-h61', 'General', 'General', 'of the French forces in Bordeaux', 1),
        ('Gentleman-aw', 'Gentleman', 'Gentleman', null, 9),
        ('Gentleman-h8', 'Gentleman', 'Gentleman', null, 3),
        ('gentleman-kl', 'Gentleman', 'Gent', null, 41),
        ('gentleman-oth', 'Gentleman', 'Gentleman', null, 1),
        ('Gentleman-r3', 'Gentleman', 'Gentleman', null, 1),
        ('Gentleman-wt', 'Gentleman', 'Gentleman', null, 5),
        ('Gentlemen-r3', 'Gentlemen', 'GENTLEMEN', null, 1),
        ('gentlewoman-cor', 'Gentlewoman', 'Gentlewoman', 'attending on Virgilia', 1),
        ('gentlewoman-mac', 'Gentlewoman', 'Gentlewoman', null, 11),
        ('gents-ham', 'Gentlemen', 'Gentlemen', null, 1),
        ('GeorgePlantagenet', 'George Plantagenet (Duke of Clarence)', 'GEORGE', null, 72),
        ('gertrude', 'Gertrude', 'Queen', 'Queen of Denmark and mother to Hamlet', 72),
        ('Girl-r3', 'Girl', 'Girl', null, 3),
        ('glendower', 'Glendower', 'GLENDOWER', null, 23),
        ('Gloucester', 'Duke of Gloucester', 'GLOUCESTER', 'brother to the King', 285),
        ('glouchester', 'Earl of Glouchester', 'Glou', null, 118),
        ('goneril', 'Goneril', 'Gon', 'daughter to Lear', 53),
        ('Gonzalo', 'Gonzalo', 'GONZALO', 'an honest old counsellor', 52),
        ('GovHarfleur', 'Governor of Harfleur', 'GOVERNOR', null, 1),
        ('gower', 'Gower', 'GOWER', null, 31),
        ('Gower-per', 'Gower', 'GOWER', 'as chorus', 8),
        ('Grandpre', 'Grandpre', 'GRANDPRE', 'French lord', 1),
        ('gratiano', 'Gratiano', 'GRATIANO', 'Brother to Brabantio', 20),
        ('Gratiano-mv', 'Gratiano', 'GRATIANO', 'friend to Antonio and Bassiano', 48),
        ('Green', 'Green', 'GREEN', 'servant to King Richard II', 10),
        ('gregory', 'Gregory', 'GREGORY', 'Servant to Gregory', 16),
        ('gremio', 'Gremio', 'GREMIO', null, 58),
        ('grey', 'Sir Thomas Grey', 'GREY', null, 5),
        ('Griffith', 'Griffith', 'GRIFFITH', 'gentleman-usher to Queen Katherine', 13),
        ('Groom', 'Groom', 'Groom', null, 4),
        ('groom1', 'First Groom', 'FIRST GROOM', null, 1),
        ('groom2', 'Second Groom', 'SECOND GROOM', null, 1),
        ('groom3', 'Third Groom', 'THIRD GROOM', null, 1),
        ('grumio', 'Grumio', 'GRUMIO', 'Petruchio''s man', 63),
        ('Guard', 'Guard', 'Guard', null, 2),
        ('Guiderius', 'Guiderius', 'GUIDERIUS', 'son to Cymbeline, disguised under the name of Polydote, supposed son to Morgan', 62),
        ('guildenstern', 'Guildenstern', 'Guil', 'courtier', 29),
        ('Guildford', 'Sir Henry Guildford', 'GUILDFORD', null, 1),
        ('Gurney', 'James Gurney', 'GURNEY', 'servant to Lady Faulconbridge', 1),
        ('haberdasher', 'Haberdasher', 'HABERDASHER', null, 1),
        ('hamgent', 'Gentleman', 'Gent', 'courtier', 2),
        ('hamghost', 'Father''s Ghost', 'Ghost', 'Ghost of Hamlet''s Father', 15),
        ('hamlet', 'Hamlet', 'Ham', 'son of the former king and nephew to the present king', 358),
        ('hamplayers', 'Players', null, null, 0),
        ('hampriest', 'Priest', 'Priest', null, 2),
        ('harcourt', 'Harcourt', 'HARCOURT', null, 1),
        ('hastings', 'Lord Hastings', 'HASTINGS', null, 17),
        ('hecate', 'Hecate', 'HECATE', null, 2),
        ('Hector', 'Hector', 'HECTOR', 'son of Priam, king of Troy', 57),
        ('Helen', 'Helen', 'HELEN', 'wife to Menelaus', 17),
        ('HELENA', 'Helena', 'HELENA', 'a gentlewoman protected by the Countess', 109),
        ('Helena-mnd', 'Helena', 'HELENA', 'in love with Demetrius', 36),
        ('Helen-cym', 'Helen', 'HELEN', 'a lady attending on Cymbeline', 0),
        ('Helenus', 'Helenus', 'HELENUS', 'son of Priam, king of Troy', 1),
        ('Helicanus', 'Helicanus', 'HELICANUS', 'a lord of Tyre', 37),
        ('henry4', 'Henry IV', 'KING HENRY IV', 'King of England', 154),
        ('henry5', 'Henry V', 'HENRY5', 'Prince, King of England', 377),
        ('Henry6', 'Henry VI', 'KING HENRY VI', null, 183),
        ('Henry7', 'Richmond (Henry VII)', 'King Henry VII', 'Earl of Richmond, later Henry VII', 14),
        ('Henry8', 'Henry VIII', 'KING HENRY VIII', null, 81),
        ('HenryBeaufort', 'Winchester', 'BISHOP OF WINCHESTER', 'Henry Beaufort, great-uncle to Henry V, bishop of Winchster, and later cardinal', 58),
        ('herald-cor', 'Herald', 'Herald', null, 2),
        ('herald-h5', 'Herald', 'Herald', null, 1),
        ('Herald-h62', 'Herald', 'Herald', null, 1),
        ('herald-kl', 'Herald', 'Her', null, 4),
        ('herald-oth', 'Herald', 'Herald', null, 1),
        ('Hermia', 'Hermia', 'HERMIA', 'daughter to Egeus, in love with Lysander', 48),
        ('Hermione', 'Hermione', 'HERMIONE', 'queen to Leontes', 35),
        ('hero', 'Hero', 'HERO', 'Daughter to Leonato', 44),
        ('Hippolyta', 'Hippolyta', 'HIPPOLYTA', 'queen of the Amazons, betrothed to Theseus', 14),
        ('Holofernes', 'Holofernes', 'HOLOFERNES', 'a schoolmaster', 54),
        ('horatio', 'Horatio', 'Hor', 'friend to Hamlet', 109),
        ('hortensio', 'Hortensio', 'HORTENSIO', null, 70),
        ('Hortensius', 'Hortensius', 'HORTENSIUS', null, 6),
        ('Host', 'Host', 'Host', 'where Julia lodges', 16),
        ('hostess-ts', 'Hostess', 'HOSTESS', null, 3),
        ('hotspur', 'Hotspur (Henry Percy)', 'HOTSPUR', null, 114),
        ('Hubert', 'Hubert de Burgh', 'HUBERT', null, 52),
        ('Huntsman', 'Huntsman', 'Huntsman', null, 2),
        ('huntsman1', 'First Huntsman', 'FIRST HUNTSMAN', null, 4),
        ('huntsman2', 'Second Huntsman', 'SECOND HUNTSMAN', null, 2),
        ('hymen', 'Hymen', 'HYMEN', null, 1),
        ('Iachimo', 'Iachimo', 'IACHIMO', 'friend to Philario, an Italian.', 77),
        ('iago', 'Iago', 'IAGO', 'Othello''s ancient (?)', 272),
        ('Imogen', 'Imogen', 'IMOGEN', 'daughter to Cymbeline by a former queen', 118),
        ('Iras', 'Iras', 'IRAS', 'attendant on Cleopatra', 18),
        ('Iris', 'Iris', 'IRIS', 'presented by spirits', 4),
        ('Isabel', 'Queen Isabel', 'QUEEN ISABEL', null, 5),
        ('Isabella-m4m', 'Isabella', 'ISABELLA', 'sister to Claudio', 129),
        ('JackCade', 'Jack Cade', 'CADE', 'a rebel', 61),
        ('Jamy', 'Jamy', 'JAMY', null, 4),
        ('Jaquenetta', 'Jaquenetta', 'JAQUENETTA', 'a country wench', 13),
        ('jaques1', 'Jaques (lord)', 'JAQUES', 'the Duke''s brother, and usurper of his dominions', 57),
        ('jaques2', 'Jaques (son)', 'JAQUES DE BOYS', 'the Duke''s brother, and usurper of his dominions', 2),
        ('Jessica', 'Jessica', 'JESSICA', 'daughter to Shylock', 26),
        ('Jeweller', 'Jeweller', 'Jeweller', null, 4),
        ('JoanPucelle', 'Joan la Pucelle', 'JOAN LA PUCELLE', 'commonly called Joan of Arc', 46),
        ('JohnGaunt', 'John of Gaunt', 'JOHN OF GAUNT', 'duke of Lancaster, uncle to the king', 28),
        ('JohnHolland', 'John Holland', 'HOLLAND', 'a follower of Cade', 10),
        ('JohnHume', 'Father John Hume', 'HUME', 'a priest', 6),
        ('JohnMorton', 'John Morton', 'BISHOP OF ELY', 'bishop of Ely', 6),
        ('JohnSouthwell', 'Father John Southwell', 'JOHN SOUTHWELL', 'a priest', 0),
        ('joseph-ts', 'Joseph', 'JOSEPH', 'a servingman', 1),
        ('Jourdain', 'Margaret Jourdain', 'MARGARET JOURDAIN', 'a witch', 1),
        ('Julia-tg', 'Julia', 'JULIA', 'beloved of Proteus', 107),
        ('juliet', 'Juliet', 'JULIET', 'Daughter to Capulet', 118),
        ('Juliet-m4m', 'Juliet', 'JULIET', 'beloved of Claudio', 7),
        ('juliuscaesar', 'Caesar', 'CAESAR', '(Julius Caesar)', 42),
        ('juniusbrutus', 'Junius Brutus', 'BRUTUS', 'tribune of the people', 91),
        ('Juno', 'Juno', 'JUNO', 'presented by spirits', 2),
        ('Jupiter', 'Jupiter', 'Jupiter', null, 1),
        ('Justice', 'Justice', 'Justice', null, 3),
        ('Katharine-h5', 'Katharine', 'KATHARINE', 'daughter to Charles and Isabel', 33),
        ('Katharine-iii', 'Katharine', 'KATHARINE', 'lady attending on the princess', 25),
        ('katherina', 'Katherina', 'KATHERINA', 'the shrew', 82),
        ('Keeper', 'Keeper', 'Keeper', null, 4),
        ('Keeper-h8', 'Keeper', 'Keeper', null, 5),
        ('kent', 'Earl of Kent', null, null, 0),
        ('kingfrance-aw', 'King of France', 'KING', null, 87),
        ('kingfrance-kl', 'King of France', 'France', null, 5),
        ('kingjohn', 'King John', 'KING JOHN', 'king of England', 95),
        ('KingPhilip', 'King Phillip', 'KING PHILIP', 'king of France', 43),
        ('knight-kl', 'Knight', 'Knight', null, 5),
        ('Knights', 'Knights', 'Knights', null, 3),
        ('LadyAnne', 'Lady Anne', 'LADY ANNE', 'widow of Edward Prince of Wales, son to King Henry VI; afterwards married to Richard III', 51),
        ('ladycapulet', 'Lady Capulet', 'LADY CAPULET', 'Wife to Capulet', 45),
        ('Lady-cym', 'Lady', 'Lady', null, 8),
        ('LadyFaulconbridge', 'Lady Faulconbridge', 'LADY FAULCONBRIDGE', 'wife to Sir Robert Faulconbridge', 5),
        ('Lady-kr2', 'Lady', 'Lady', 'attending on the Queen', 6),
        ('ladymacbeth', 'Lady Macbeth', 'LADY MACBETH', null, 59),
        ('ladymacduff', 'Lady Macduff', 'LADY MACDUFF', null, 19),
        ('ladymontague', 'Lady Montague', 'LADY MONTAGUE', 'Wife to Montague', 2),
        ('ladynorth', 'Lady Northumberland', 'LADY NORTHUMBERLAND', null, 2),
        ('ladypercy', 'Lady Percy', 'LADY PERCY', null, 18),
        ('laertes', 'Laertes', 'Laer', 'son to Polonius', 62),
        ('LAFEU', 'Lafeu', 'LAFEU', 'an old lord', 97),
        ('lancaster', 'John of Lancaster', null, 'son of King Henry IV', 0),
        ('lartius', 'Titus Lartius', 'TITUS', 'general against the Volscians', 23),
        ('Launce', 'Launce', 'LAUNCE', 'the like to Proteus', 68),
        ('Launcelot', 'Launcelot Gobbo', 'LAUNCELOT', 'the clown, servant to Shylock', 44),
        ('Lavinia', 'Lavinia', 'LAVINIA', null, 15),
        ('Lawyer', 'Lawyer', 'Lawyer', null, 2),
        ('lear', 'Lear', 'Lear', 'King of Britain', 188),
        ('lebeau', 'Le Beau', 'LE BEAU', 'a courtier attending upon Frederick', 14),
        ('legate', 'Legate', 'Legate', null, 1),
        ('lennox', 'Lennox', 'LENNOX', 'Nobleman of Scotland', 21),
        ('Leonardo', 'Leonardo', 'LEONARDO', 'servant to Bassiano', 2),
        ('leonato', 'Leonato', 'LEONATO', 'Governor of Messina', 120),
        ('Leonatus', 'Sicilius Leonatus', 'Sicilius Leonatus', 'an apparition', 7),
        ('Leonine', 'Leonine', 'LEONINE', 'servant to Dionyza', 12),
        ('Leontes', 'Leontes', 'LEONTES', 'king of Sicilia', 125),
        ('lepidus', 'Lepidus', 'LEPIDUS', '(Marcus Antonius Lepidus)', 33),
        ('Lewis', 'Lewis', 'LEWIS', 'the Dauphin', 29),
        ('Lewis11', 'King Lewis XI', 'KING LEWIS XI', 'king of France', 21),
        ('lieutenant', 'Lieutenant', 'LIEUTENANT', 'to Aufidius', 4),
        ('Lieutenant-h62', 'Lieutenant', 'Lieutenant', 'of the Tower', 1),
        ('Ligarius', 'Ligarius', 'LIGARIUS', 'a conspirator against Caesar', 5),
        ('lodovico', 'Lodovico', 'LODOVICO', 'Kinsman to Brabantio', 33),
        ('Longaville', 'Longaville', 'LONGAVILLE', 'lord attending on the king', 40),
        ('lord-ayli', 'Lord', 'LORD', null, 2),
        ('LordBerkeley', 'Lord Berkeley', 'LORD BERKELEY', null, 2),
        ('LordChamberlain', 'Lord Chamberlain', 'Chamberlain', null, 38),
        ('LordChancellor', 'Lord Chancellor', 'Chancellor', null, 7),
        ('LordClifford', 'Lord Clifford', 'CLIFFORD', null, 52),
        ('Lord-cym', 'Lord', 'Lord', null, 6),
        ('LordFitzwater', 'Lord Fitzwater', 'LORD FITZWATER', null, 6),
        ('LordGrey', 'Lord Grey', 'GREY', 'son of Queen Elizabeth', 6),
        ('lord-ham', 'Lord', 'Lord', null, 3),
        ('LordHastings-63', 'Lord Hastings', 'HASTINGS', null, 56),
        ('Lord-kr2', 'Lord', 'Lord', null, 1),
        ('LordLovel', 'Lord Lovel', 'LOVEL', null, 2),
        ('lord-ma', 'Lord', 'Lord', null, 1),
        ('lord-mac', 'Lord', 'Lord', null, 3),
        ('LordMarshal', 'Lord Marshal', 'LORD MARSHAL', null, 10),
        ('Lord-per', 'Lord', 'Lord', null, 4),
        ('LordRivers', 'Lord (Earl) Rivers', 'RIVERS', 'brother to Lady Gray (Queen Elizabeth)', 29),
        ('LordSands', 'Lord Sands', 'SANDS', null, 17),
        ('LordSay', 'Lord Say', 'SAY', null, 13),
        ('LordScales', 'Lord Scales', 'SCALES', null, 2),
        ('lordscroop', 'Lord Scroop', 'SCROOP', null, 5),
        ('Lords-cym', 'Lords', 'Lords', null, 0),
        ('lords-mac', 'Lords', 'Lords', null, 3),
        ('Lords-r3', 'Lords', 'LORDS', null, 3),
        ('LordStafford', 'Lord Stafford', 'STAFFORD', null, 0),
        ('Lords-wt', 'Lords', 'Lords', null, 2),
        ('lord-ts', 'Lord', 'LORD', null, 17),
        ('LordWilloughby', 'Lord Willoughby', 'LORD WILLOUGHBY', null, 8),
        ('Lord-wt', 'Lord', 'Lord', null, 4),
        ('Lorenzo', 'Lorenzo', 'LORENZO', 'in love with Jessica', 47),
        ('Lovell', 'Sir Thomas Lovell', 'LOVELL', null, 21),
        ('LUCE', 'Luce', 'LUCE', 'servant to Adriana', 7),
        ('lucentio', 'Lucentio', 'LUCENTIO', 'son to Vincentio, in love with Bianca', 61),
        ('Lucetta', 'Lucetta', 'LUCETTA', 'waiting-woman to Julia', 48),
        ('LUCIANA', 'Luciana', 'LUCIANA', 'sister to Adriana', 43),
        ('lucianus', 'Lucianus', 'Luc', null, 0),
        ('Lucilius', 'Lucilius', 'LUCILIUS', 'servant to Timon', 13),
        ('Lucilius-jc', 'Lucilius', 'LUCILIUS', 'friend to Brutus', 10),
        ('LuciliusServant', 'Lucilius'' Servant', 'Lucilius'' Servant', null, 0),
        ('Lucio', 'Lucio', 'LUCIO', 'a fantastic', 111),
        ('Lucius', 'Lucius', 'LUCIUS', 'son to Titus Andronicus', 51),
        ('Lucius-jc', 'Lucius', 'LUCIUS', 'servant to Brutus', 24),
        ('Lucius-tim', 'Lucius', 'LUCIUS', 'flattering lord', 0),
        ('Lucullus', 'Lucullus', 'LUCULLUS', 'flattering lord', 6),
        ('Lychorida', 'Lychorida', 'LYCHORIDA', 'nurse to Marina', 4),
        ('Lymoges', 'Lymoges', 'AUSTRIA', 'duke of Austria', 16),
        ('Lysander', 'Lysander', 'LYSANDER', 'in love with Hermia', 50),
        ('Lysimachus', 'Lysimachus', 'LYSIMACHUS', 'governor of Mytilene', 40),
        ('macbeth', 'Macbeth', 'MACBETH', 'General of the King''s army', 146),
        ('macduff', 'Macduff', 'MACDUFF', 'Nobleman of Scotland', 59),
        ('macmorris', 'Macmorris', 'MACMORRIS', null, 4),
        ('malcolm', 'Malcolm', 'MALCOLM', 'Son of Duncan', 40),
        ('MALVOLIO', 'Malvolio', 'MALVOLIO', 'steward to Olivia', 87),
        ('Mamillius', 'Mamillius', 'MAMILLIUS', 'young prince of Sicilia', 13),
        ('Man-h8', 'Man', 'Man', 'the Porter''s man', 6),
        ('marcellus', 'Marcellus', 'Mar', 'Officer', 37),
        ('MarcusAndronicus', 'Marcus Andronicus', 'MARCUS ANDRONICUS', 'tribune of the people, and brother to Titus', 63),
        ('Mardian', 'Mardian', 'MARDIAN', 'a eunuch, attendant on Cleopatra', 7),
        ('Margarelon', 'Margarelon', 'MARGARELON', 'a bastard son of Priam', 3),
        ('margaret', 'Margaret', 'MARGARET', 'Gentlewoman attending on Hero', 26),
        ('Margaret-h61', 'Queen Margaret', 'Margaret', 'daughter to Reignier, afterwards married to King Henry VI', 169),
        ('MargaretPlantagenet', 'Margaret Plantagenet', 'MARGARET PLANTAGENET', 'a young daughter of Clarence', 0),
        ('MARIA', 'Maria', 'MARIA', 'Olivia''s woman', 59),
        ('Maria-lll', 'Maria', 'MARIA', 'lady attending on the princess', 22),
        ('MARIANA', 'Mariana', 'MARIANA', 'neighbor and friend to the widow', 5),
        ('Mariana-m4m', 'Mariana', 'MARIANA', null, 24),
        ('Marina', 'Marina', 'MARINA', 'daughter to Pericles and Thaisa', 63),
        ('Mariners', 'Mariners', 'Mariners', null, 1),
        ('Mariner-wt', 'Mariner', 'Mariner', null, 3),
        ('MarquessMontague', 'Marquess of Montague', 'MONTAGUE', null, 15),
        ('MarquisDorset', 'Marquis of Dorset', 'DORSET', 'son of Queen Elizabeth', 10),
        ('Marshal', 'Marshal', 'Marshal', null, 1),
        ('martext', 'Sir Oliver Martext', 'MARTEXT', 'a vicar', 3),
        ('Martius', 'Martius', 'MARTIUS', 'son to Titus Andronicus', 10),
        ('Marullus', 'Marullus', 'MARULLUS', 'a tribune', 6),
        ('Master', 'Master', 'Master', null, 1),
        ('Master-Gunner', 'Master-Gunner', 'Master-Gunner', 'of Orleans', 2),
        ('MasterShip', 'Master', 'Master', 'master of a ship', 2),
        ('MatthewGoffe', 'Matthew Goffe', 'MATTHEW GOFFE', null, 0),
        ('MayorAlbans', 'Mayor of Saint Alban''s', 'Mayor', null, 2),
        ('MayorLondon', 'Lord Mayor of London', 'Mayor', null, 14),
        ('MayorYork', 'Mayor of York', 'Mayor', null, 3),
        ('Mecaenas', 'Mecaenas', 'MECAENAS', 'friend to Caesar', 16),
        ('Melun', 'Melun', 'MELUN', 'a French Lord', 3),
        ('Menas', 'Menas', 'MENAS', 'friend to Caesar', 35),
        ('Menecrates', 'Menecrates', 'MENECRATES', 'friend to Pompey', 2),
        ('Menelaus', 'Menelaus', 'MENELAUS', 'Agamemnon''s brother', 11),
        ('menenius', 'Menenius Agrippa', 'MENENIUS', 'friend to Coriolanus', 162),
        ('menteith', 'Menteith', 'MENTEITH', 'Nobleman of Scotland', 5),
        ('Mercade', 'Mercade', 'MERCADE', 'lord attending on the princess of France', 3),
        ('Merchant', 'Merchant', 'Merchant', null, 8),
        ('mercutio', 'Mercutio', 'MERCUTIO', 'Kinsman to Escalus the prince, and friend to Romeo', 62),
        ('Messala', 'Messala', 'MESSALA', 'friend to Brutus', 20),
        ('Messenger-ac', 'Messenger', 'Messenger', null, 42),
        ('Messenger-cor', 'Messenger', 'Messenger', null, 12),
        ('Messenger-cym', 'Messenger', 'Messenger', null, 2),
        ('Messenger-h41', 'Messenger', 'Messenger', null, 6),
        ('messenger-h4p2', 'Messenger', 'MESSENGER', null, 1),
        ('Messenger-h5', 'Messenger', 'Messenger', null, 4),
        ('Messenger-h61', 'Messenger', 'Messenger', null, 14),
        ('Messenger-h62', 'Messenger', 'Messenger', null, 5),
        ('Messenger-h63', 'Messenger', 'Messenger', null, 6),
        ('Messenger-h8', 'Messenger', 'Messenger', null, 2),
        ('messenger-ham', 'Messenger', 'Mess', null, 3),
        ('Messenger-jc', 'Messenger', 'Messenger', null, 1),
        ('Messenger-kjo', 'Messenger', 'Messenger', null, 9),
        ('messenger-kl', 'Messenger', 'Mess', null, 1),
        ('Messenger-m4m', 'Messenger', 'Messenger', null, 1),
        ('messenger-ma', 'Messenger', 'Messenger', null, 17),
        ('messenger-mac', 'Messenger', 'Messenger', null, 6),
        ('messenger-oth', 'Messenger', 'Messenger', null, 2),
        ('Messenger-per', 'Messenger', 'Messenger', null, 1),
        ('Messenger-r3', 'Messenger', 'Messenger', null, 13),
        ('Messenger-ta', 'Messenger', 'Messenger', null, 1),
        ('Messenger-tim', 'Messenger', 'Messenger', null, 6),
        ('messenger-ts', 'Messenger', 'MESSENGER', null, 1),
        ('MetellusCimber', 'Metellus Cimber', 'Metellus Cimber', 'a conspirator against Caesar', 5),
        ('Michael', 'Michael', 'MICHAEL', 'a follower of Cade', 3),
        ('Miranda', 'Miranda', 'MIRANDA', 'daughter to Prospero', 49),
        ('mistressford', 'Mistress Ford', 'MISTRESS FORD', null, 85),
        ('MistressOverdone', 'Mistress Overdone', 'MISTRESS OVERDONE', 'a bawd', 15),
        ('mistresspage', 'Mistress Page', 'MISTRESS PAGE', null, 101),
        ('montague', 'Montague', 'MONTAGUE', 'Head of the house of Montague', 10),
        ('montano', 'Montano', 'MONTANO', 'Othello''s predecessor in the government of Cyprus', 24),
        ('Montjoy', 'Montjoy', 'MONTJOY', 'a French herald', 11),
        ('Mopsa', 'Mopsa', 'MOPSA', 'a shepherdess', 13),
        ('mortimer', 'Mortimer', 'MORTIMER', 'Earl of March', 13),
        ('morton', 'Morton', 'MORTON', 'retainer of Northumberland', 6),
        ('Moth', 'Moth', 'MOTH', 'page to Armado', 78),
        ('Mother', 'Mother', 'Mother', 'an apparition', 3),
        ('Moth-mnd', 'Moth', 'MOTH', 'a fairy', 2),
        ('mouldy', 'Ralph Mouldy', 'MOULDY', 'country soldier', 5),
        ('mowbray', 'Lord Mowbray', 'MOWBRAY', null, 18),
        ('Mustardseed', 'Mustardseed', 'MUSTARDSEED', 'a fairy', 5),
        ('Mutius', 'Mutius', 'MUTIUS', 'son to Titus Andronicus', 3),
        ('Myrmidons', 'Myrmidons', 'MYRMIDONS', 'soldiers of Achilles in the Trojan war', 1),
        ('nathaniel-ts', 'Nathaniel', 'NATHANIEL', 'a servingman', 4),
        ('Nerissa', 'Nerissa', 'NERISSA', 'Portia''s maid-in-waiting', 36),
        ('Nestor', 'Nestor', 'NESTOR', 'a Greek prince', 38),
        ('nicholas-ts', 'Nicholas', 'NICHOLAS', 'a servingman', 1),
        ('Nobleman-h63', 'Nobleman', 'Nobleman', null, 1),
        ('norcapt', 'Norwegian Captain', 'Capt', null, 7),
        ('nurse-rj', 'Nurse', 'Nurse', 'Nurse to Juliet', 90),
        ('Nurse-ta', 'Nurse', 'Nurse', null, 10),
        ('nym', 'Nym', 'NYM', 'sharper attending on Falstaff', 33),
        ('Nymphs', 'Nymphs', 'Nymphs', 'presented by spirits', 0),
        ('Oberon', 'Oberon', 'OBERON', 'king of the fairies', 29),
        ('Octavia', 'Octavia', 'OCTAVIA', 'sister to Caesar and wife to Antony', 13),
        ('octavius', 'Octavius', 'OCTAVIUS', '(Octavius Caesar)', 117),
        ('Officer-ce', 'Officer', 'Officer', null, 11),
        ('Officer-cor', 'Officer', 'Officer', null, 1),
        ('Officer-h61', 'Officer', 'Officer', null, 1),
        ('Officer-wt', 'Officer', 'Officer', null, 5),
        ('OldAthenian', 'Old Athenian', 'Old Athenian', null, 10),
        ('OldGobbo', 'Old Gobbo', 'GOBBO', 'father to Launcelot', 19),
        ('OldLady-h8', 'Old Lady', 'Old Lady', 'friend to Anne Bullen', 14),
        ('oldman-kl', 'Old Man', 'Old Man', 'tenant to Glouchester', 9),
        ('oldman-mac', 'Old Man', 'Old Man', null, 4),
        ('OldShepherd', 'Old Shepherd', 'Shepherd', 'reputed father of Perdita', 42),
        ('oliver', 'Oliver', 'OLIVER', 'son of Sir Rowland de Boys', 37),
        ('OLIVIA', 'Olivia', 'OLIVIA', null, 118),
        ('ophelia', 'Ophelia', 'Oph', 'daughter to Polonius', 58),
        ('orlando', 'Orlando', 'ORLANDO', 'son of Sir Rowland de Boys', 120),
        ('orleans', 'Duke of Orleans', 'ORLEANS', null, 29),
        ('ORSINO', 'Orsino', 'DUKE ORSINO', 'Duke of Illyria', 59),
        ('osric', 'Osric', 'Osr', 'courtier', 25),
        ('Ostler', 'Ostler', 'Ostler', null, 1),
        ('oswald', 'Oswald', 'Osw', 'steward to Goneril', 38),
        ('othello', 'Othello', 'OTHELLO', 'A noble Moor in the service of the Ventian state', 274),
        ('Outlaws', 'Outlaws', 'Outlaws', null, 1),
        ('page1-ayli', 'First Page', 'FIRST PAGE', null, 3),
        ('page2-ayli', 'Second Page', 'SECOND PAGE', null, 2),
        ('Page-aw', 'Page', 'Page', null, 1),
        ('page-h4p2', 'Page', 'PAGE', 'to Falstaff', 17),
        ('Page-h8', 'Page', 'Boy', 'a page to Gardiner', 1),
        ('page-mww', 'Page', 'PAGE', 'a gentleman dwelling at Windsor', 75),
        ('Page-r3', 'Page', 'Page', null, 3),
        ('page-rj', 'Page', 'PAGE', 'Page to Paris', 4),
        ('Page-tim', 'Page', 'Page', null, 4),
        ('page-ts', 'Page', 'PAGE', null, 8),
        ('Painter', 'Painter', 'Painter', null, 30),
        ('Pandar', 'Pandar', 'Pandar', null, 10),
        ('Pandarus', 'Pandarus', 'PANDARUS', 'uncle to Cressida', 153),
        ('Panthino', 'Panthino', 'PANTHINO', 'servant to Antonio', 14),
        ('paris', 'Paris', 'PARIS', 'A young nobleman, kinsman to Escalus the prince', 23),
        ('Paris-tc', 'Paris', 'PARIS', 'son of Priam, king of Troy', 27),
        ('PAROLLES', 'Parolles', 'PAROLLES', 'a follower of Bertram', 141),
        ('Patience', 'Patience', 'PATIENCE', 'woman to Queen Katharine', 3),
        ('patrician', 'Patrician', 'A Patrician', null, 3),
        ('Patroclus', 'Patroclus', 'PATROCLUS', 'a Greek prince', 37),
        ('Paulina', 'Paulina', 'PAULINA', 'wife to Antigonus', 59),
        ('Peaseblossom', 'Peaseblossom', 'PEASEBLOSSOM', 'a fairy', 4),
        ('pedant', 'Pedant', 'PEDANT', null, 20),
        ('Pembroke', 'Pembroke', 'PEMBROKE', 'earl of Pembroke', 20),
        ('Pembroke-h63', 'Earl of Pembroke', 'PEMBROKE', null, 0),
        ('Perdita', 'Perdita', 'PERDITA', 'daughter to Leontes and Hermione', 25),
        ('Pericles', 'Pericles', 'PERICLES', 'prince of Tyre', 121),
        ('Peter-h62', 'Peter', 'PETER', 'Thomas Horner''s man', 9),
        ('PeterPomfret', 'Peter of Pomfret', 'PETER', 'a prophet', 1),
        ('peter-rj', 'Peter', 'PETER', 'Servant to Julet''s nurse', 13),
        ('peter-ts', 'Peter', 'PETER', 'a servingman', 2),
        ('peto', 'Peto', 'PETO', null, 8),
        ('petruchio', 'Petruchio', 'PETRUCHIO', 'a gentleman of Verona, a suitor to Katherina', 158),
        ('phebe', 'Phebe', 'PHEBE', 'a shepherdess', 23),
        ('Philario', 'Philario', 'PHILARIO', 'friend to Posthumus, an Italian.', 14),
        ('Philemon', 'Philemon', 'PHILEMON', 'servant to Cerimon', 1),
        ('PhilipBastard', 'Philip the Bastard', 'BASTARD', 'illegitimate son of Sir Robert Faulconbridge', 89),
        ('philip-ts', 'Philip', 'PHILIP', 'a servingman', 1),
        ('Philo', 'Philo', 'PHILO', 'friend to Antony', 2),
        ('Philostrate', 'Philostrate', 'PHILOSTRATE', 'master of the revels to Theseus', 6),
        ('Philotus', 'Philotus', 'PHILOTUS', 'servant to Timon''s creditors', 6),
        ('Phrynia', 'Phrynia', 'PHRYNIA', 'mistress to Alcibiades', 4),
        ('PINCH', 'Pinch', 'PINCH', 'a schoolmaster', 6),
        ('Pindarus', 'Pindarus', 'PINDARUS', 'servant to Cassius', 5),
        ('Pisanio', 'Pisanio', 'PISANIO', 'servant to Posthumus', 58),
        ('pistol', 'Pistol', 'PISTOL', null, 122),
        ('players-ts', 'Players', 'PLAYERS', null, 1),
        ('player-ts', 'Player', 'PLAYER', null, 3),
        ('Poet', 'Poet', 'Poet', 'the voice of Shakespeare''s poetry', 733),
        ('Poet-jc', 'Poet', 'Poet', null, 3),
        ('Poet-tim', 'Poet', 'Poet', null, 30),
        ('poins', 'Edward Poins', 'POINS', null, 64),
        ('Polixenes', 'Polixenes', 'POLIXENES', 'king of Bohemia', 57),
        ('polonius', 'Polonius', 'Pol', 'Lord Chamberlain', 86),
        ('Pompey', 'Pompey', 'POMPEY', '(Sextus Pompeius)', 41),
        ('Pompey-m4m', 'Pompey', 'POMPEY', 'servant to Mistress Overdone', 60),
        ('Popilius', 'Popilius', 'POPILIUS', '(Popilius Lena)', 2),
        ('porter', 'Porter', 'PORTER', null, 2),
        ('Porter-h61', 'Porter', 'Porter', null, 1),
        ('Porter-h8', 'Porter', 'Porter', 'door-keeper of the Council-chamber', 10),
        ('porter-mac', 'Porter', 'Porter', null, 4),
        ('Portia', 'Portia', 'PORTIA', 'wife to Brutus', 16),
        ('Portia-mv', 'Portia', 'PORTIA', 'a rich heiress', 117),
        ('Post-h62', 'Post', 'Post', null, 1),
        ('Post-h63', 'Post', 'Post', null, 9),
        ('PosthumusLeonatus', 'Posthumus Leonatus', 'POSTHUMUS LEONATUS', 'a gentleman, husband to Imogen', 77),
        ('Priam', 'Priam', 'PRIAM', 'king of Troy', 6),
        ('Priest-12', 'Priest', 'Priest', null, 1),
        ('Priest-r3', 'Priest', 'Priest', null, 1),
        ('PrinceArragon', 'Prince of Arragon', 'ARRAGON', 'suitor to Portia', 4),
        ('PrinceEdward', 'Prince Edward', 'PRINCE EDWARD', null, 35),
        ('PrinceHenry', 'Prince Henry', 'PRINCE HENRY', 'son to King John', 8),
        ('princehumphrey', 'Prince Humphrey', 'PRINCE HUMPHREY', 'of Goucester', 11),
        ('princejohn', 'Prince John', 'LANCASTER', 'of Lancaster', 31),
        ('PrinceMorocco', 'Prince of Morocco', 'MOROCCO', 'suitor to Portia', 7),
        ('Princes-r3', 'Princes', 'Princes', null, 1),
        ('PrincessFrance', 'Princess of France', 'PRINCESS', null, 102),
        ('Proculeius', 'Proculeius', 'PROCULEIUS', 'friend to Caesar', 10),
        ('Prospero', 'Prospero', 'PROSPERO', 'the rightful Duke of Milan', 115),
        ('Proteus', 'Proteus', 'PROTEUS', 'a gentleman', 147),
        ('Provost', 'Provost', 'Provost', null, 65),
        ('Publius', 'Publius', 'PUBLIUS', 'son to Marcus the Tribune', 5),
        ('publius-jc', 'Publius', 'PUBLIUS', 'Senator', 2),
        ('Puck', 'Puck', 'PUCK', 'or Robin Goodfellow', 33),
        ('Pursuivant', 'Pursuivant', 'Pursuivant', null, 3),
        ('Queen-cym', 'Queen', 'QUEEN', 'wife to Cymbeline', 27),
        ('QueenElinor', 'Queen Elinor', 'QUEEN ELINOR', 'mother to King John', 22),
        ('QueenElizabeth', 'Queen Elizabeth', 'QUEEN ELIZABETH', 'starts as Lady Grey, marries Edward IV', 129),
        ('QueenKatharine', 'Queen Katharine', 'QUEEN KATHARINE', 'wife to King Henry, afterwards divorced', 50),
        ('Queen-kr2', 'Queen', 'QUEEN', null, 25),
        ('quickly', 'Hostess Quickly', 'HOSTESS', 'hostess of a tavern in Eastcheap', 158),
        ('Quince', 'Quince', 'QUINCE', 'a carpenter', 40),
        ('Quintus', 'Quintus', 'QUINTUS', 'son to Titus Andronicus', 11),
        ('Rambures', 'Rambures', 'RAMBURES', 'French lord', 5),
        ('Reapers', 'Reapers', 'Reapers', 'presented by spirits', 0),
        ('regan', 'Regan', 'Reg', 'daughter to Lear', 73),
        ('Reignier', 'Reignier', 'REIGNIER', 'duke of Anjou, and titular king of Naples', 24),
        ('reynaldo', 'Reynaldo', 'Rey', 'servant to Polonius', 13),
        ('Richard2', 'King Richard II', 'KING RICHARD II', 'king of England', 98),
        ('Sempronius-tim', 'Sempronius', 'SEMPRONIUS', 'flattering lord', 2),
        ('Richard3', 'Richard III', 'RICHARD3', 'son of Richard Plantagenet, duke of York; was duke of Gloucester before enthronement', 246),
        ('RichardPlantagenet', 'Richard Plantagenet (Duke of Gloucester)', 'PLANTAGENET', 'becomes duke of York in Henry VI, Part', 172),
        ('RichardPlantagenet2', 'Richard Plantagenet the Younger', 'RICHARD', null, 6),
        ('robin', 'Robin', 'ROBIN', 'page to Falstaff', 6),
        ('roderigo', 'Roderigo', 'RODERIGO', 'A Venetian gentleman', 59),
        ('RomanCaptain', 'Roman Captain', 'Captain', null, 4),
        ('Roman-cor', 'Roman', 'Roman', null, 10),
        ('romeo', 'Romeo', 'ROMEO', 'Son to Montague', 163),
        ('rosalind', 'Rosalind', 'ROSALIND', 'daughter to the banished Duke', 201),
        ('Rosaline-lll', 'Rosaline', 'ROSALINE', 'lady attending on the princess', 75),
        ('rosencrantz', 'Rosencrantz', 'Ros', 'courtier', 48),
        ('ross', 'Ross', 'ROSS', 'Nobleman of Scotland', 39),
        ('Ross-kr2', 'Lord Ross', 'LORD ROSS', null, 11),
        ('rugby', 'Rugby', 'RUGBY', 'servant to Doctor Caius', 9),
        ('rumour', 'Rumour', 'RUMOUR', 'the Presenter', 1),
        ('sailor-ham', 'Sailor', 'Sailor', null, 2),
        ('sailor-oth', 'Sailor', 'Sailor', null, 2),
        ('Salanio', 'Salanio', 'SALANIO', 'friend to Antonio and Bassiano', 18),
        ('Salarino', 'Salarino', 'SALARINO', 'friend to Antonio and Bassiano', 27),
        ('Salerio', 'Salerio', 'SALERIO', 'friend to Antonio and Bassiano', 6),
        ('salisbury', 'Earl of Salisbury', 'SALISBURY', null, 23),
        ('Salisbury-kj', 'Salisbury', 'SALISBURY', 'earl of Salisbury', 36),
        ('Salisbury-kr2', 'Earl of Salisbury', 'EARL OF SALISBURY', null, 3),
        ('sampson', 'Sampson', 'SAMPSON', 'Servant to Capulet', 20),
        ('Saturninus', 'Saturninus', 'SATURNINUS', 'son to the late Emperor of Rome, and afterwards
	declared Emperor', 49),
        ('Scarus', 'Scarus', 'SCARUS', 'friend to Antony', 12),
        ('Scout-h61', 'Scout', 'Scout', null, 2),
        ('Scribe-h8', 'Scribe', 'Scribe', null, 2),
        ('Scrivener', 'Scrivener', 'Scrivener', null, 1),
        ('scroop', 'Archbishop Scroop', 'ARCHBISHOP', 'Archbishop of York', 30),
        ('SeaCaptain', 'Captain', 'Captain', 'friend to Viola', 10),
        ('SEBASTIAN', 'Sebastian', 'SEBASTIAN', 'brother to Viola', 31),
        ('Sebastian-tem', 'Sebastian', 'SEBASTIAN', 'the King''s brother', 67),
        ('SecondAttendant', 'Second Attendant', 'Second Attendant', null, 1),
        ('SecondBandit', 'Second Bandit', 'Second Bandit', null, 4),
        ('SecondBrother', 'Second Brother', 'Second Brother', 'an apparition', 2),
        ('SecondCaptain-cym', 'Second British Captain', 'Second Captain', null, 2),
        ('SecondCarrier', 'Second Carrier', 'Second Carrier', null, 6),
        ('SecondCitizen', 'Second Citizen', 'Second Citizen', null, 18),
        ('SecondCitizen-jc', 'Second Citizen', 'Second Citizen', null, 18),
        ('SecondCitizen-r3', 'Second Citizen', 'Second Citizen', null, 6),
        ('SecondCommoner', 'Second Commoner', 'Second Commoner', null, 6),
        ('SecondFish', 'Second Fisherman', 'Second Fisherman', null, 12),
        ('SecondGaoler', 'Second Gaoler', 'Second Gaoler', null, 1),
        ('SecondGentleman', 'Second Gentleman', 'Second Gentleman', null, 9),
        ('SecondGentleman-aw', 'Second Gentleman', 'Second Gentleman', null, 5),
        ('SecondGentleman-cym', 'Second Gentleman', 'Second Gentleman', 'a gentleman of Cymbeline''s court', 9),
        ('SecondGentleman-h62', 'Second Gentleman', 'Second Gentleman', null, 1),
        ('SecondGentleman-h8', 'Second Gentleman', 'Second Gentleman', null, 37),
        ('SecondGentleman-wt', 'Second Gentleman', 'Second Gentleman', null, 4),
        ('SecondGent-per', 'Second Gentleman', 'Second Gentleman', null, 10),
        ('SecondGuard', 'Second Guard', 'Second Guard', null, 4),
        ('SecondHerald-kr2', 'Second Herald', 'Second Herald', null, 1),
        ('SecondKeeper', 'Second Keeper', 'Second Keeper', null, 9),
        ('SecondKnight-per', 'Second Knight', 'Second Knight', null, 1),
        ('SecondLady-wt', 'Second Lady', 'Second Lady', null, 3),
        ('SecondLord', 'Second Lord', 'Second Lord', null, 3),
        ('SecondLord-aw', 'Second Lord', 'Second Lord', null, 57),
        ('secondlord-ayli', 'Second Lord', 'SECOND LORD', null, 2),
        ('SecondLord-cym', 'Second Lord', 'Second Lord', 'a lord of Cymbeline''s court', 20),
        ('SecondLord-per', 'Second Lord', 'Second Lord', null, 4),
        ('SecondLord-tim', 'Second Lord', 'Second Lord', null, 29),
        ('SecondMerchant', 'Second Merchant', 'Second Merchant', 'indebted to Angelo', 13),
        ('SecondMessenger', 'Second Messenger', 'Second Messenger', null, 1),
        ('SecondMessenger-ac', 'Second Messenger', 'Second Messenger', null, 2),
        ('SecondMessenger-cor', 'Second Messenger', 'Second Messenger', null, 5),
        ('SecondMessenger-h63', 'Second Messenger', 'Second Messenger', null, 1),
        ('SecondMurderer-h62', 'Second Murderer', 'Second Murderer', null, 1),
        ('SecondMurderer-r3', 'Second Murderer', 'Second Murderer', null, 30),
        ('SecondNeighbour-h62', 'Second Neighbour', 'Second Neighbour', null, 1),
        ('SecondOfficer-12', 'Second Officer', 'Second Officer', null, 3),
        ('SecondOfficer-ac', 'Second Officer', 'Second Officer', null, 0),
        ('SecondOfficer-cor', 'Second Officer', 'Second Officer', null, 3),
        ('SecondOutlaw', 'Second Outlaw', 'Second Outlaw', null, 10),
        ('SecondPetitioner-h62', 'Second Petitioner', 'Second Petitioner', null, 3),
        ('SecondPirate', 'Second Pirate', 'Second Pirate', null, 1),
        ('SecondPrentice', 'Second ''Prentice', 'Second ''Prentice', null, 0),
        ('SecondRoman', 'Second Roman', 'Second Roman', null, 1),
        ('SecondSailor-per', 'Second Sailor', 'Second Sailor', null, 4),
        ('SecondSecretary', 'Second Secretary', 'Second Secretary', 'to Wolsey', 0),
        ('SecondSenator-cym', 'Second Senator', 'Second Senator', null, 1),
        ('SecondSenator-tim', 'Second Senator', 'Second Senator', null, 14),
        ('SecondSentinel', 'Second Sentinel', 'Second Sentinel', null, 0),
        ('SecondServant-ac', 'Second Servant', 'Second Servant', null, 3),
        ('SecondServant-mww', 'Second Servant', 'Second Servant', null, 1),
        ('SecondServant-tim', 'Second Servant', 'Second Servant', null, 5),
        ('SecondServant-wt', 'Second Servant', 'Second Servant', null, 1),
        ('SecondServiceman', 'Second Serviceman', 'Second Serviceman', null, 0),
        ('SecondServingman', 'Second Servingman', 'Second Servingman', null, 19),
        ('SecondSoldier-ac', 'Second Soldier', 'Second Soldier', null, 11),
        ('SecondSoldier-aw', 'Second Soldier', 'Second Soldier', null, 2),
        ('SecondSoldier-jc', 'Second Soldier', 'Second Soldier', null, 2),
        ('SecondStranger', 'Second Stranger', 'Second Stranger', null, 3),
        ('SecondWarder', 'Second Warder', 'Second Warder', null, 1),
        ('SecondWatchman-h63', 'Second Watchman', 'Second Watchman', null, 5),
        ('Seleucus', 'Seleucus', 'SELEUCUS', 'attendant on Cleopatra', 3),
        ('Sempronius', 'Sempronius', 'SEMPRONIUS', 'kinsman to Titus', 0),
        ('senator-oth', 'Senator', null, 'A senator of Venice', 0),
        ('Senator-tim', 'Senator', 'Senator', null, 4),
        ('Sentinels', 'Sentinels', 'Sentinels', null, 1),
        ('Sergeant-h61', 'Sergeant', 'Sergeant', null, 1),
        ('Sergeant-h8', 'Sergeant', 'Sergeant', 'a sergeant-at-arms', 1),
        ('sergeant-mac', 'Sergeant', 'Sergeant', null, 3),
        ('Servant', 'Servant', 'Servant', 'servant to Diomedes', 15),
        ('Servant-12', 'Servant', 'Servant', null, 1),
        ('servant1-kl', 'Servant 1', 'Serv1', null, 4),
        ('servant1-ts', 'First Servant', 'FIRST SERVANT', null, 6),
        ('servant2-kl', 'Servant 2', 'Serv2', null, 2),
        ('servant2-ts', 'Second Servant', 'SECOND SERVANT', null, 4),
        ('servant3-kl', 'Servant 3', 'Serv3', null, 2),
        ('servant3-ts', 'Third Servant', 'THIRD SERVANT', null, 4),
        ('Servant-aw', 'Servant', 'Servant', null, 1),
        ('Servant-ce', 'Servant', 'Servant', null, 2),
        ('Servant-h41', 'Servant', 'Servant', null, 3),
        ('servant-h4p2', 'Servant', 'SERVANT', null, 7),
        ('Servant-h61', 'Servant', 'Servant', null, 1),
        ('Servant-h62', 'Servant', 'Servant', null, 1),
        ('Servant-h8', 'Servant', 'Servant', null, 1),
        ('servant-ham', 'Servant', 'Servant', null, 1),
        ('Servant-jc', 'Servant', 'Servant', null, 11),
        ('Servant-kr2', 'Servant', 'Servant', null, 8),
        ('Servant-m4m', 'Servant', 'Servant', null, 3),
        ('servant-mac', 'Servant', 'Servant', null, 5),
        ('Servant-mv', 'Servant', 'Servant', null, 4),
        ('servant-mww', 'Servant', 'Servant', null, 1),
        ('Servant-per', 'Servant', 'Servant', null, 1),
        ('servant-rj', 'Servant', 'Servant', null, 10),
        ('Servants-h62', 'Servants', 'Servants', null, 1),
        ('servants-ts', 'Servants', 'ALL SERVANTS', null, 1),
        ('Servant-tim', 'Servant', 'Servant', null, 9),
        ('servant-ts', 'Servant', 'SERVANT', null, 2),
        ('Servant-wt', 'Servant', 'Servant', null, 10),
        ('Servilius', 'Servilius', 'SERVILIUS', 'servant to Timon', 8),
        ('servingmen', 'Serving-Men', 'Serving-Men', null, 1),
        ('SeventhCitizen', 'Seventh Citizen', 'Seventh Citizen', null, 1),
        ('SeveralCitizens', 'Several Citizens', 'Several Citizens', null, 2),
        ('sexton-ma', 'Sexton', 'Sexton', null, 7),
        ('seyton', 'Seyton', 'SEYTON', 'An officer attending on Macduff', 5),
        ('shadow', 'Simon Shadow', 'SHADOW', 'country soldier', 2),
        ('shallow', 'Robert Shallow', 'SHALLOW', 'country Justice', 136),
        ('Shepherd-h61', 'Shepherd', 'Shepherd', 'father to Joan of Arc', 4),
        ('sheriff-h41', 'Sheriff', 'Sheriff', null, 5),
        ('Sheriff-h62', 'Sheriff', 'Sheriff', null, 2),
        ('SheriffWiltshire', 'Sheriff of Wiltshire', 'Sheriff', null, 2),
        ('Shylock', 'Shylock', 'SHYLOCK', 'a rich Jew', 79),
        ('sicinius', 'Sicinius Velutus', 'SICINIUS', 'tribune of the people', 117),
        ('silence', 'Silence', 'SILENCE', 'country Justice', 22),
        ('Silius', 'Silius', 'SILIUS', 'an officer in Ventidius''s army', 3),
        ('Silvia', 'Silvia', 'SILVIA', 'beloved of Valentine', 58),
        ('silvius', 'Silvius', 'SILVIUS', 'daughter to the banished Duke', 24),
        ('Simonides', 'Simonides', 'SIMONIDES', 'king of Pentapolis', 42),
        ('Simpcox', 'Simpcox', 'SIMPCOX', 'an imposter', 18),
        ('simple', 'Simple', 'SIMPLE', 'servant to Slender', 25),
        ('sirhugh', 'Sir Hugh Evans', 'SIR HUGH EVANS', 'a Welsh parson', 87),
        ('SirHughMortimer', 'Sir Hugh Mortimer', 'HUGH MORTIMER', 'uncle to the Duke of York', 0),
        ('SirHumphrey', 'Sir Humphrey Stafford', 'SIR HUMPHREY', 'brother to William Stafford', 6),
        ('SirJamesBlount', 'Sir James Blount', 'Blount', null, 0),
        ('SirJamesTyrrel', 'Sir James Tyrrel', 'TYRREL', null, 10),
        ('SirJohnFastolfe', 'Sir John Fastolfe', 'FASTOLFE', null, 3),
        ('SirJohnMontgomery', 'Sir John Montgomery', 'MONTGOMERY', null, 0),
        ('SirJohnMortimer', 'Sir John Mortimer', 'JOHN MORTIMER', 'uncle to the Duke of York', 1),
        ('SirJohnSomerville', 'Sir John Somerville', 'SOMERVILLE', null, 0),
        ('SirJohnStanley', 'Sir John Stanley', 'STANLEY', null, 4),
        ('sirmichael', 'Sir Michael', 'SIR MICHAEL', 'a friend to the Archbishop of York', 4),
        ('SirNathaniel', 'Sir Nathaniel', 'SIR NATHANIEL', 'a curate', 19),
        ('SirRichardRatcliff', 'Sir Richard Ratcliff', 'RATCLIFF', null, 18),
        ('SirRobertBrakenbury', 'Sir Robert Brakenbury', 'BRAKENBURY', null, 16),
        ('SirScroop', 'Sir Stephen Scroop', 'SIR STEPHEN SCROOP', null, 6),
        ('SirThomasGargrave', 'Sir Thomas Gargrave', 'GARGRAVE', null, 2),
        ('SirThomasVaughan', 'Sir Thomas Vaughan', 'VAUGHAN', null, 2),
        ('SirWalterHerbert', 'Sir Walter Herbert', 'HERBERT', null, 1),
        ('SirWilliamCatesby', 'Sir William Catesby', 'CATESBY', null, 31),
        ('SirWilliamGlansdale', 'Sir  William Glansdale', 'GLANSDALE', null, 1),
        ('SirWilliamLucy', 'Sir William Lucy', 'LUCY', null, 14),
        ('SirWilliamStanley', 'Sir William Stanley', 'STANLEY', 'called also Earl of Derby', 32),
        ('siward', 'Siward', 'SIWARD', 'Earl of Northumberland, general of English forces', 11),
        ('SixthCitizen', 'Sixth Citizen', 'Sixth Citizen', null, 1),
        ('slender', 'Slender', 'SLENDER', 'cousin to Shallow', 56),
        ('sly', 'Christopher Sly', 'SLY', 'a tinker', 24),
        ('SmithWeaver', 'Smith the Weaver', 'SMITH', 'a follower of Cade', 9),
        ('snare', 'Snare', 'SNARE', 'a Sheriff''s officer', 2),
        ('Snout', 'Snout', 'SNOUT', 'a tinker', 9),
        ('Snug', 'Snug', 'SNUG', 'a joiner', 4),
        ('Soldier-ac', 'Soldier', 'Soldier', null, 13),
        ('Soldier-h61', 'Soldier', 'Soldier', null, 1),
        ('Soldier-h62', 'Soldier', 'Soldier', null, 1),
        ('Soldier-h63', 'Soldier', 'Soldier', null, 1),
        ('soldiers-mac', 'Soldiers', 'Soldiers', null, 1),
        ('Soldier-tim', 'Soldier', 'Soldier', null, 2),
        ('SOLINUS', 'Solinus', 'DUKE SOLINUS', 'Duke of Ephesus', 22),
        ('SomeOthers', 'Some Others', 'Some Others', null, 1),
        ('Somerset', 'Duke/Earl of Somerset', 'SOMERSET', 'John Beaufort', 52),
        ('SomeSpeak', 'Some Speak', 'Some Speak', null, 1),
        ('Son-h63', 'Son', 'Son', 'who has killed his father', 4),
        ('son-mac', 'Son', 'Son', 'Macduff''s son', 14),
        ('Soothsayer', 'Soothsayer', 'Soothsayer', null, 9),
        ('Soothsayer-ac', 'Soothsayer', 'Soothsayer', null, 14),
        ('Soothsayer-cym', 'Soothsayer', 'Soothsayer', null, 5),
        ('Speed', 'Speed', 'SPEED', 'a clownish servant to Valentine', 117),
        ('Spirit', 'Spirit', 'Spirit', null, 5),
        ('Starveling', 'Starveling', 'STARVELING', 'a tailor', 7),
        ('Stephano', 'Stephano', 'STEPHANO', 'servant to Portia', 3),
        ('Stephano-tem', 'Stephano', 'STEPHANO', 'a drunken butler', 60),
        ('Steward-aw', 'Steward', 'Steward', 'servant to the Countess', 6),
        ('Strato', 'Strato', 'STRATO', 'servant to Brutus', 4),
        ('surrey', 'Earl of Surrey', null, null, 0),
        ('Surveyor', 'Surveyor', 'Surveyor', 'to the Duke of Buckingham', 9),
        ('tailor', 'Tailor', 'TAILOR', null, 12),
        ('Talbot', 'Lord Talbot/Earl of Shrewsbury', 'JOHN TALBOT', null, 70),
        ('Tamora', 'Tamora', 'TAMORA', null, 49),
        ('Taurus', 'Taurus', 'TAURUS', 'lieutenant-general to Caesar', 1),
        ('tearsheet', 'Doll Tearsheet', 'DOLL', null, 31),
        ('Thaisa', 'Thaisa', 'THAISA', 'daughter to Simonides', 32),
        ('Thaliard', 'Thaliard', 'THALIARD', 'a lord of Antioch', 8),
        ('Thersites', 'Thersites', 'THERSITES', 'a deformed and scurrilous Greek', 90),
        ('Theseus', 'Theseus', 'THESEUS', 'Duke of Athens', 48),
        ('thieves', 'Thieves', 'Thieves', null, 1),
        ('ThirdBandit', 'Third Bandit', 'Third Bandit', null, 3),
        ('ThirdCitizen', 'Third Citizen', 'Third Citizen', null, 13),
        ('ThirdCitizen-jc', 'Third Citizen', 'Third Citizen', null, 16),
        ('ThirdCitizen-r3', 'Third Citizen', 'Third Citizen', null, 9),
        ('ThirdFish', 'Third Fisherman', 'Third Fisherman', null, 6),
        ('ThirdGentleman-h8', 'Third Gentleman', 'Third Gentleman', null, 10),
        ('ThirdGentleman-wt', 'Third Gentleman', 'Third Gentleman', null, 6),
        ('ThirdGuard', 'Third Guard', 'Third Guard', null, 1),
        ('ThirdKnight-per', 'Third Knight', 'Third Knight', null, 1),
        ('ThirdLord', 'Third Lord', 'Third Lord', null, 1),
        ('ThirdLord-aw', 'Third Lord', 'Third Lord', null, 0),
        ('ThirdLord-per', 'Third Lord', 'Third Lord', null, 2),
        ('ThirdLord-tim', 'Third Lord', 'Third Lord', null, 11),
        ('ThirdMessenger', 'Third Messenger', 'Third Messenger', null, 3),
        ('ThirdNeighbour-h62', 'Third Neighbour', 'Third Neighbour', null, 1),
        ('ThirdOfficer-ac', 'Third Officer', 'Third Officer', null, 0),
        ('ThirdOutlaw', 'Third Outlaw', 'Third Outlaw', null, 8),
        ('ThirdPirate', 'Third Pirate', 'Third Pirate', null, 1),
        ('ThirdRoman', 'Third Roman', 'Third Roman', null, 1),
        ('ThirdSenator', 'Third Senator', 'Third Senator', null, 2),
        ('ThirdServant-tim', 'Third Servant', 'Third Servant', null, 2),
        ('ThirdServiceman', 'Third Serviceman', 'Third Serviceman', null, 0),
        ('ThirdServingman', 'Third Servingman', 'Third Servingman', null, 20),
        ('ThirdSoldier-ac', 'Third Soldier', 'Third Soldier', null, 10),
        ('ThirdSoldier-jc', 'Third Soldier', 'Third Soldier', null, 1),
        ('ThirdStranger', 'Third Stranger', 'Third Stranger', null, 1),
        ('ThirdWatchman-h63', 'Third Watchman', 'Third Watchman', null, 3),
        ('ThMowbray', 'Thomas Mowbray', 'THOMAS MOWBRAY', 'Duke of Norfolk', 13),
        ('thomas-h4p2', 'Prince Thomas', 'CLARENCE', 'Duke of Clarence', 13),
        ('ThomasHorner', 'Thomas Horner', 'HORNER', 'an armourer', 6),
        ('ThomasRotherham', 'Thomas Rotherham', 'ARCHBISHOP OF YORK', 'archbishop of York', 5),
        ('Thurio', 'Thurio', 'THURIO', 'a foolish rival to Valentine', 36),
        ('Thyreus', 'Thyreus', 'THYREUS', 'friend to Caesar', 12),
        ('Timandra', 'Timandra', 'TIMANDRA', 'mistress to Alcibiades', 3),
        ('Time', 'Time', 'Time', 'as the chorus', 1),
        ('Timon', 'Timon', 'TIMON', null, 210),
        ('Tintinius', 'Tintinius', 'Tintinius', 'friend to Brutus', 10),
        ('Titania', 'Titania', 'TITANIA', 'queen of the fairies', 23),
        ('TitusAndronicus', 'Titus Andronicus', 'TITUS ANDRONICUS', 'a noble Roman, general against the Goths.', 117),
        ('Titus-tim', 'Titus', 'TITUS', 'servant to Timon''s creditors', 12),
        ('touchstone', 'Touchstone', 'TOUCHSTONE', 'the court jester', 74),
        ('Townsman-h62', 'Townsman', 'Townsman', null, 2),
        ('tranio', 'Tranio', 'TRANIO', null, 90),
        ('Travellers', 'Travellers', 'Travellers', null, 2),
        ('travers', 'Travers', 'TRAVERS', 'retainer of Northumberland', 1),
        ('Trebonius', 'Trebonius', 'TREBONIUS', 'a conspirator against Caesar', 4),
        ('Tressel', 'Tressel', 'TRESSEL', 'a gentleman attending on Lady Anne', 0),
        ('Tribunes-ta', 'Tribunes', 'Tribunes', null, 1),
        ('Trinculo', 'Trinculo', 'TRINCULO', 'a jester', 39),
        ('Troilus', 'Troilus', 'TROILUS', 'son of Priam, king of Troy', 131),
        ('Tubal', 'Tubal', 'TUBAL', 'a Jew, his friend', 8),
        ('tullus', 'Tullus Aufidius', 'AUFIDIUS', 'general of the Vulscians', 45),
        ('TutorRutland', 'Tutor of Rutland', 'Tutor', null, 2),
        ('tybalt', 'Tybalt', 'TYBALT', 'Nephew to Lady Capulet', 17),
        ('TyrianSailor', 'Tyrian Sailor', 'Tyrian Sailor', null, 3),
        ('Ulysses', 'Ulysses', 'ULYSSES', 'a Greek prince', 80),
        ('ursula', 'Ursula', 'URSULA', 'Gentlewoman attending on Hero', 19),
        ('Valentine', 'Valentine', 'VALENTINE', 'kinsman to Titus', 0),
        ('VALENTINE-12', 'Valentine', 'VALENTINE', 'gentleman attending on the Duke', 3),
        ('Valentine-tg', 'Valentine', 'VALENTINE', 'a gentleman', 149),
        ('valeria', 'Valeria', 'VALERIA', 'friend to Virgilia', 14),
        ('Varrius', 'Varrius', 'VARRIUS', 'friend to Pompey', 1),
        ('Varrius-m4m', 'Varrius', 'VARRIUS', null, 0),
        ('Varro', 'Varro', 'VARRO', 'servant to Brutus', 6),
        ('VarroFirst', 'Varro''s First Servant', 'Varro''s First Servant', null, 0),
        ('VarroSecond', 'Varro''s Second Servant', 'Varro''s Second Servant', null, 0),
        ('Vaux', 'Sir Nicholas Vaux', 'VAUX', null, 1),
        ('Vaux-h62', 'Vaux', 'VAUX', null, 1),
        ('Ventidius', 'Ventidius', 'VENTIDIUS', 'one of Timon''s false friends', 2),
        ('Ventidius-ac', 'Ventidius', 'VENTIDIUS', 'friend to Antony', 4),
        ('verges', 'Verges', 'VERGES', 'A headborough', 18),
        ('Vernon', 'Vernon', 'VERNON', 'of the White Rose, or York, faction', 26),
        ('vincentio', 'Vincentio', 'VINCENTIO', 'a merchant of Pisa', 23),
        ('Vincentio-m4m', 'Vincentio', 'DUKE VINCENTIO', 'the Duke', 194),
        ('Vintner', 'Vintner', 'Vintner', null, 1),
        ('VIOLA', 'Viola', 'VIOLA', null, 121),
        ('VIOLENTA', 'Violenta', 'VIOLENTA', 'neighbor and friend to the widow', 0),
        ('virgilia', 'Virgilia', 'VIRGILIA', 'wife to Coriolanus', 26),
        ('Volsce', 'Volsce', 'Volsce', null, 9),
        ('voltemand', 'Voltemand', 'Volt', 'courtier', 1),
        ('volumnia', 'Volumnia', 'VOLUMNIA', 'mother to Coriolanus', 57),
        ('Volumnius', 'Volumnius', 'VOLUMNIUS', 'friend to Brutus', 3),
        ('WalterWhitmore', 'Walter Whitmore', 'WHITMORE', null, 8),
        ('wart', 'Thomas Wart', 'WART', 'country soldier', 2),
        ('warwick', 'Earl of Warwick', 'WARWICK', null, 182),
        ('Watch-h61', 'Watch', 'Watch', null, 2),
        ('watchman-ma', 'Watchman', 'Watchman', null, 10),
        ('westmoreland', 'Earl of Westmoreland', 'WESTMORELAND', null, 39),
        ('widow', 'Widow', 'WIDOW', null, 8),
        ('WidowFlorence', 'Widow', 'Widow', 'an old widow of Florence', 21),
        ('WifeSimpcox', 'Simpcox''s Wife', 'Wife', null, 7),
        ('william-ayli', 'William', 'WILLIAM', 'a country fellow, in love with Audrey', 11),
        ('Williams', 'Williams', 'WILLIAMS', 'soldier in King Henry''s army', 28),
        ('wmpage', 'William Page', 'WILLIAM PAGE', 'a boy, son to Page', 11),
        ('WmStafford', 'William Stafford', 'WILLIAM STAFFORD', 'brother to Sir Humphrey Stafford', 5),
        ('Wolsey', 'Cardinal Wolsey', 'CARDINAL WOLSEY', null, 79),
        ('Woodvile', 'Woodvile', 'WOODVILE', 'lieutenant of the Tower', 2),
        ('worcester', 'Earl of Worcester', 'EARL OF WORCESTER', null, 35),
        ('xxx', '(stage directions)', 'xxx', null, 126),
        ('york', 'Duke of York', 'YORK', 'cousin to the king', 1),
        ('YoungClifford', 'Young Clifford', 'YOUNG CLIFFORD', null, 4),
        ('YoungCoriolanus', 'Young Coriolanus', 'Young CORIOLANUS', 'son to Coriolanus', 1),
        ('YoungLucius', 'Young Lucius', 'Young LUCIUS', 'son to Lucius', 11),
        ('youngsiward', 'Young Siward', 'YOUNG SIWARD', 'Siward''s son', 4);